export interface Book {
  id: string;
  name: string;
  testament: 'OT' | 'NT';
  bollsBook: number;
  chapters: number;
  author: string;
  date: string;
  audience: string;
  purpose: string;
  overview: string;
  themes: string[];
  keyPeople: string[];
  keyEvents: string[];
  structure: { range: string; title: string }[];
}

export const BOOKS: Book[] = [
  {
    id: 'genesis',
    name: 'Genesis',
    testament: 'OT',
    bollsBook: 1,
    chapters: 50,
    author: 'Traditionally Moses',
    date: 'c. 1440–1400 BC',
    audience: 'The Israelites preparing to enter the Promised Land',
    purpose: 'To reveal God as Creator and covenant-maker, and to trace the origins of humanity, sin, and the chosen people Israel.',
    overview:
      'Genesis is the book of beginnings: the creation of the world, the fall of humanity, the flood, and the scattering of the nations. The second half follows the patriarchs — Abraham, Isaac, Jacob, and Joseph — through whom God establishes the covenant that will shape the rest of Scripture. It ends with Israel in Egypt, setting the stage for the Exodus.',
    themes: ['Creation', 'The fall and sin', 'Covenant', 'Promise and fulfillment', 'Providence of God', 'Faith'],
    keyPeople: ['Adam', 'Eve', 'Noah', 'Abraham', 'Sarah', 'Isaac', 'Jacob', 'Joseph'],
    keyEvents: [
      'The creation of the world (ch. 1–2)',
      'The fall and expulsion from Eden (ch. 3)',
      'The flood and the covenant with Noah (ch. 6–9)',
      'The tower of Babel (ch. 11)',
      'The call of Abraham (ch. 12)',
      'The covenant with Abraham (ch. 15, 17)',
      'The binding of Isaac (ch. 22)',
      'Joseph sold into Egypt and his rise to power (ch. 37–50)',
    ],
    structure: [
      { range: '1–11', title: 'Primeval history: creation to Babel' },
      { range: '12–25', title: 'The life of Abraham' },
      { range: '25–36', title: 'Isaac and Jacob' },
      { range: '37–50', title: 'Joseph and Israel in Egypt' },
    ],
  },
  {
    id: 'exodus',
    name: 'Exodus',
    testament: 'OT',
    bollsBook: 2,
    chapters: 40,
    author: 'Traditionally Moses',
    date: 'c. 1440–1400 BC',
    audience: 'The Israelites in the wilderness and beyond',
    purpose: 'To show God redeeming His people from slavery, forming them into His covenant nation, and dwelling among them.',
    overview:
      'Exodus tells how God delivered Israel from Egyptian bondage through Moses and the ten plagues, the Passover, and the parting of the Red Sea. At Mount Sinai, Israel receives the Law — including the Ten Commandments — and the pattern for the tabernacle, the dwelling place of God among His people. It is the central salvation story of the Old Testament.',
    themes: ['Redemption', 'Covenant law', 'Presence of God', 'Deliverance', 'Worship', 'Faithfulness vs. rebellion'],
    keyPeople: ['Moses', 'Aaron', 'Miriam', 'Pharaoh', 'Jethro', 'Joshua', 'Bezalel'],
    keyEvents: [
      'The birth and call of Moses (ch. 2–4)',
      'The ten plagues (ch. 7–12)',
      'The Passover and the Exodus (ch. 12)',
      'Crossing the Red Sea (ch. 14)',
      'Manna and water in the wilderness (ch. 16–17)',
      'The Ten Commandments at Sinai (ch. 20)',
      'The golden calf (ch. 32)',
      'The building of the tabernacle (ch. 35–40)',
    ],
    structure: [
      { range: '1–18', title: 'Deliverance from Egypt' },
      { range: '19–24', title: 'The covenant at Sinai' },
      { range: '25–31', title: 'Instructions for the tabernacle' },
      { range: '32–40', title: 'Rebellion and the tabernacle built' },
    ],
  },
  {
    id: 'leviticus',
    name: 'Leviticus',
    testament: 'OT',
    bollsBook: 3,
    chapters: 27,
    author: 'Traditionally Moses',
    date: 'c. 1440–1400 BC',
    audience: 'The Israelites, especially the priests (Levites)',
    purpose: 'To teach God\'s people how a holy God dwells among a sinful people — through sacrifice, priesthood, and holy living.',
    overview:
      'Leviticus lays out the sacrificial system, the consecration of priests, purity laws, and the feasts of Israel. At its center stands the Day of Atonement, when the high priest makes atonement for the sins of the nation. The book\'s refrain is God\'s call: "Be holy, for I am holy" — a standard later quoted in the New Testament.',
    themes: ['Holiness', 'Sacrifice and atonement', 'The priesthood', 'Purity', 'Worship', 'Obedience'],
    keyPeople: ['Moses', 'Aaron', 'Nadab and Abihu', 'Eleazar', 'Ithamar'],
    keyEvents: [
      'The five offerings instituted (ch. 1–7)',
      'The consecration of Aaron and his sons (ch. 8–9)',
      'The death of Nadab and Abihu (ch. 10)',
      'Laws of purity (ch. 11–15)',
      'The Day of Atonement (ch. 16)',
      'The feasts of the LORD (ch. 23)',
      'Blessings and curses (ch. 26)',
    ],
    structure: [
      { range: '1–7', title: 'Laws of sacrifice' },
      { range: '8–10', title: 'The priesthood established' },
      { range: '11–16', title: 'Purity laws and the Day of Atonement' },
      { range: '17–27', title: 'The Holiness Code: feasts, laws, blessings' },
    ],
  },
  {
    id: 'numbers',
    name: 'Numbers',
    testament: 'OT',
    bollsBook: 4,
    chapters: 36,
    author: 'Traditionally Moses',
    date: 'c. 1440–1400 BC',
    audience: 'The second generation of Israelites before entering Canaan',
    purpose: 'To record the wilderness wanderings and show the consequences of unbelief alongside God\'s faithfulness to His promises.',
    overview:
      'Numbers follows Israel\'s 40-year journey from Sinai to the plains of Moab. A census opens and closes the book — hence the name. The older generation\'s rebellion at Kadesh-Barnea condemns them to die in the desert, while the new generation learns to trust God through hardship. It ends with Israel poised to enter the Promised Land.',
    themes: ['Faith vs. unbelief', 'God\'s faithfulness', 'Judgment', 'Provision', 'Leadership', 'Preparation'],
    keyPeople: ['Moses', 'Aaron', 'Joshua', 'Caleb', 'Korah', 'Balaam', 'Phinehas'],
    keyEvents: [
      'The census of Israel (ch. 1)',
      'The report of the spies and rebellion (ch. 13–14)',
      'Korah\'s rebellion (ch. 16)',
      'The bronze serpent (ch. 21)',
      'Balaam and Balak (ch. 22–24)',
      'The second census (ch. 26)',
    ],
    structure: [
      { range: '1–10', title: 'Preparation at Sinai' },
      { range: '11–20', title: 'Rebellion and wandering' },
      { range: '21–36', title: 'The new generation moves toward Canaan' },
    ],
  },
  {
    id: 'deuteronomy',
    name: 'Deuteronomy',
    testament: 'OT',
    bollsBook: 5,
    chapters: 34,
    author: 'Traditionally Moses (with Joshua\'s addition at the end)',
    date: 'c. 1400 BC',
    audience: 'The new generation of Israelites at the edge of the Promised Land',
    purpose: 'To renew the covenant with the next generation and call them to love and obey God wholeheartedly.',
    overview:
      'Deuteronomy is Moses\' farewell: three sermons delivered on the plains of Moab as the new generation prepares to enter Canaan. He retells the law, urges exclusive devotion to God, and sets before them blessing for obedience and curse for disobedience. The book closes with Moses\' death and the commissioning of Joshua.',
    themes: ['Covenant renewal', 'Love for God', 'Obedience', 'Blessing and curse', 'Remembrance', 'One God'],
    keyPeople: ['Moses', 'Joshua', 'Caleb', 'Phinehas'],
    keyEvents: [
      'Moses\' first sermon: recounting the journey (ch. 1–4)',
      'The Ten Commandments restated (ch. 5)',
      'The Shema: love the LORD your God (ch. 6)',
      'Blessings and curses (ch. 27–28)',
      'The covenant renewed (ch. 29–30)',
      'The death of Moses (ch. 34)',
    ],
    structure: [
      { range: '1–4', title: 'Moses\' first sermon: history' },
      { range: '5–26', title: 'Second sermon: the law restated' },
      { range: '27–30', title: 'Third sermon: blessing, curse, covenant' },
      { range: '31–34', title: 'Farewell of Moses' },
    ],
  },
  {
    id: 'joshua',
    name: 'Joshua',
    testament: 'OT',
    bollsBook: 6,
    chapters: 24,
    author: 'Traditionally Joshua (with later additions)',
    date: 'c. 1400–1370 BC',
    audience: 'The Israelites settled in Canaan',
    purpose: 'To show God fulfilling His promise by giving Israel the land, calling them to courageous obedience.',
    overview:
      'Joshua records the conquest of Canaan under Joshua\'s leadership — crossing the Jordan, the fall of Jericho, the southern and northern campaigns, and the division of the land among the tribes. The book closes with Joshua\'s famous charge: "Choose this day whom you will serve... as for me and my house, we will serve the LORD."',
    themes: ['Promise fulfilled', 'Courage and obedience', 'Holy war', 'Covenant faithfulness', 'The land'],
    keyPeople: ['Joshua', 'Rahab', 'Achan', 'Caleb', 'Phinehas', 'Eleazar'],
    keyEvents: [
      'Crossing the Jordan (ch. 3–4)',
      'The fall of Jericho (ch. 6)',
      'The sin of Achan (ch. 7)',
      'The sun stands still at Gibeon (ch. 10)',
      'Division of the land (ch. 13–21)',
      'Joshua\'s farewell and the covenant at Shechem (ch. 23–24)',
    ],
    structure: [
      { range: '1–12', title: 'The conquest of the land' },
      { range: '13–21', title: 'Division of the land' },
      { range: '22–24', title: 'Joshua\'s farewell and renewal' },
    ],
  },
  {
    id: 'judges',
    name: 'Judges',
    testament: 'OT',
    bollsBook: 7,
    chapters: 21,
    author: 'Traditionally Samuel',
    date: 'c. 1050–1000 BC',
    audience: 'The Israelites under the monarchy',
    purpose: 'To show the downward spiral of Israel without godly leadership — and God\'s grace in raising deliverers.',
    overview:
      'Judges covers the turbulent period between Joshua and the kings, when Israel repeatedly fell into idolatry, was oppressed, cried out, and was rescued by judges God raised up. The pattern grows darker with each cycle, ending in civil war. Its refrain explains the chaos: "In those days there was no king in Israel; everyone did what was right in his own eyes."',
    themes: ['Sin and repentance', 'God\'s deliverance', 'Leadership', 'Moral decline', 'Covenant unfaithfulness'],
    keyPeople: ['Deborah', 'Gideon', 'Samson', 'Jephthah', 'Othniel', 'Ehud', 'Samuel'],
    keyEvents: [
      'Othniel delivers Israel (ch. 3)',
      'Deborah and Barak defeat Sisera (ch. 4–5)',
      'Gideon and the 300 (ch. 6–8)',
      'Samson and Delilah (ch. 13–16)',
      'Micah\'s idolatry (ch. 17–18)',
      'The Benjamite civil war (ch. 19–21)',
    ],
    structure: [
      { range: '1–3', title: 'Introduction: incomplete conquest' },
      { range: '3–16', title: 'The cycles of the judges' },
      { range: '17–21', title: 'Appendix: moral and religious collapse' },
    ],
  },
  {
    id: 'ruth',
    name: 'Ruth',
    testament: 'OT',
    bollsBook: 8,
    chapters: 4,
    author: 'Traditionally Samuel',
    date: 'c. 1050–1000 BC (set in the time of the judges)',
    audience: 'The Israelites',
    purpose: 'To show God\'s steadfast love (hesed) working through ordinary faithfulness, leading to the line of David.',
    overview:
      'Set during the dark days of the judges, Ruth tells of a Moabite widow who clings to her Israelite mother-in-law, Naomi, and to Naomi\'s God. Through her loyalty and the kindness of Boaz, a kinsman-redeemer, Ruth becomes the great-grandmother of King David. It is a tender story of redemption woven into Israel\'s history.',
    themes: ['Redemption', 'Steadfast love (hesed)', 'Providence', 'Loyalty', 'God\'s plan through ordinary lives'],
    keyPeople: ['Ruth', 'Naomi', 'Boaz', 'Orpah', 'Elimelech'],
    keyEvents: [
      'Naomi loses her husband and sons in Moab (ch. 1)',
      'Ruth\'s vow: "Your God shall be my God" (ch. 1)',
      'Ruth gleans in Boaz\'s field (ch. 2)',
      'Ruth at the threshing floor (ch. 3)',
      'Boaz redeems and marries Ruth (ch. 4)',
      'The birth of Obed, ancestor of David (ch. 4)',
    ],
    structure: [
      { range: '1', title: 'Loss and loyalty' },
      { range: '2', title: 'Providence in the fields' },
      { range: '3', title: 'The appeal at the threshing floor' },
      { range: '4', title: 'Redemption and a royal line' },
    ],
  },
  {
    id: '1-samuel',
    name: '1 Samuel',
    testament: 'OT',
    bollsBook: 9,
    chapters: 31,
    author: 'Traditionally Samuel, with Nathan and Gad',
    date: 'c. 930 BC',
    audience: 'The Israelites under the monarchy',
    purpose: 'To trace Israel\'s transition from judges to kingship, contrasting the rejected Saul with the chosen David.',
    overview:
      'First Samuel opens with the birth of Samuel, Israel\'s last judge, who anoints Saul as the people\'s demanded king. Saul\'s disobedience leads to his rejection, and the young shepherd David rises — defeating Goliath, serving at court, fleeing Saul\'s jealousy, and twice sparing his life. The book ends with Saul\'s death on Mount Gilboa.',
    themes: ['Kingship', 'Obedience vs. sacrifice', 'God looks at the heart', 'Sovereignty', 'Repentance'],
    keyPeople: ['Samuel', 'Saul', 'David', 'Jonathan', 'Hannah', 'Eli', 'Goliath', 'Abigail'],
    keyEvents: [
      'Hannah\'s prayer and Samuel\'s birth (ch. 1–2)',
      'Israel demands a king (ch. 8)',
      'Saul anointed king (ch. 9–10)',
      'Saul rejected for disobedience (ch. 15)',
      'David anointed (ch. 16)',
      'David and Goliath (ch. 17)',
      'David spares Saul\'s life (ch. 24, 26)',
      'The death of Saul (ch. 31)',
    ],
    structure: [
      { range: '1–7', title: 'Samuel: the last judge' },
      { range: '8–15', title: 'Saul: the rejected king' },
      { range: '16–31', title: 'David: the anointed king in waiting' },
    ],
  },
  {
    id: '2-samuel',
    name: '2 Samuel',
    testament: 'OT',
    bollsBook: 10,
    chapters: 24,
    author: 'Traditionally Nathan and Gad',
    date: 'c. 930 BC',
    audience: 'The Israelites under the monarchy',
    purpose: 'To record David\'s reign — his triumphs, his grievous sin, and God\'s covenant promising an eternal throne.',
    overview:
      'Second Samuel follows David\'s rise to king over all Israel, his conquest of Jerusalem, and the covenant God makes with him promising an everlasting dynasty. But David\'s adultery with Bathsheba and murder of Uriah unleash turmoil in his house — rebellion by Absalom, civil strife, and grief. The book shows both God\'s grace and the wages of sin.',
    themes: ['The Davidic covenant', 'Sin and repentance', 'God\'s faithfulness', 'Consequences', 'Worship'],
    keyPeople: ['David', 'Joab', 'Nathan', 'Absalom', 'Bathsheba', 'Uriah', 'Mephibosheth', 'Solomon'],
    keyEvents: [
      'David becomes king over all Israel (ch. 5)',
      'The ark brought to Jerusalem (ch. 6)',
      'The Davidic covenant (ch. 7)',
      'David\'s sin with Bathsheba (ch. 11)',
      'Nathan\'s rebuke and David\'s repentance (ch. 12)',
      'Absalom\'s rebellion (ch. 15–18)',
    ],
    structure: [
      { range: '1–10', title: 'David\'s triumphs' },
      { range: '11–20', title: 'David\'s troubles' },
      { range: '21–24', title: 'Appendix: songs, heroes, and judgment' },
    ],
  },
  {
    id: '1-kings',
    name: '1 Kings',
    testament: 'OT',
    bollsBook: 11,
    chapters: 22,
    author: 'Traditionally Jeremiah',
    date: 'c. 550 BC',
    audience: 'The exiles in Babylon',
    purpose: 'To show how Israel\'s kings led the nation toward judgment — and how God remained faithful through prophets like Elijah.',
    overview:
      'First Kings begins with Solomon\'s glorious reign — the temple built, wisdom famed, wealth immense — then his heart turns to foreign gods and the kingdom splits. The northern kingdom of Israel spirals through wicked kings like Ahab, confronted by the prophet Elijah. The book spans from David\'s death to Ahab\'s death.',
    themes: ['Wisdom and folly', 'Idolatry', 'The temple', 'Prophetic confrontation', 'Judgment'],
    keyPeople: ['Solomon', 'Rehoboam', 'Jeroboam', 'Ahab', 'Jezebel', 'Elijah', 'Elisha'],
    keyEvents: [
      'Solomon becomes king (ch. 1–2)',
      'Solomon\'s prayer for wisdom (ch. 3)',
      'The temple built and dedicated (ch. 6–8)',
      'The Queen of Sheba visits (ch. 10)',
      'The kingdom divides (ch. 12)',
      'Elijah on Mount Carmel (ch. 18)',
    ],
    structure: [
      { range: '1–11', title: 'The reign of Solomon' },
      { range: '12–16', title: 'The divided kingdom' },
      { range: '17–22', title: 'Elijah and the house of Ahab' },
    ],
  },
  {
    id: '2-kings',
    name: '2 Kings',
    testament: 'OT',
    bollsBook: 12,
    chapters: 25,
    author: 'Traditionally Jeremiah',
    date: 'c. 550 BC',
    audience: 'The exiles in Babylon',
    purpose: 'To record the fall of both kingdoms, explaining the exile as the consequence of persistent unfaithfulness.',
    overview:
      'Second Kings continues the downward course of Israel and Judah through the ministry of Elisha to the fall of Samaria (722 BC) and, a century later, the fall of Jerusalem (586 BC). A few faithful kings like Hezekiah and Josiah bring brief reform, but the nation\'s idolatry leads to Babylonian captivity. The book ends with a glimmer of hope for the exiled king Jehoiachin.',
    themes: ['Judgment for unfaithfulness', 'Prophetic ministry', 'Reform and revival', 'Exile', 'God\'s patience'],
    keyPeople: ['Elisha', 'Jehu', 'Hezekiah', 'Manasseh', 'Josiah', 'Nebuchadnezzar', 'Jehoiachin'],
    keyEvents: [
      'Elijah taken up; Elisha succeeds him (ch. 2)',
      'Naaman healed of leprosy (ch. 5)',
      'The fall of Samaria (ch. 17)',
      'Hezekiah\'s prayer and deliverance (ch. 19)',
      'Josiah\'s reforms (ch. 22–23)',
      'The fall of Jerusalem (ch. 25)',
    ],
    structure: [
      { range: '1–10', title: 'The divided kingdom to the fall of Samaria' },
      { range: '11–17', title: 'Israel\'s fall; Judah survives' },
      { range: '18–25', title: 'Judah\'s final years and the exile' },
    ],
  },
  {
    id: '1-chronicles',
    name: '1 Chronicles',
    testament: 'OT',
    bollsBook: 13,
    chapters: 29,
    author: 'Traditionally Ezra',
    date: 'c. 450–400 BC',
    audience: 'The returned exiles rebuilding Jerusalem',
    purpose: 'To retell Israel\'s history from a priestly perspective, encouraging the restored community with David\'s godly legacy.',
    overview:
      'First Chronicles begins with nine chapters of genealogies stretching from Adam to the returned exiles, anchoring the restoration community in God\'s story. It then focuses on David\'s reign — especially his preparations for the temple — as a model for the post-exilic people to follow.',
    themes: ['God\'s covenant with David', 'Worship', 'Genealogy and identity', 'The temple'],
    keyPeople: ['David', 'Solomon', 'Jabez', 'Joab', 'Nathan', 'Zadok'],
    keyEvents: [
      'The genealogies from Adam to the exiles (ch. 1–9)',
      'David anointed king (ch. 11)',
      'The ark brought to Jerusalem (ch. 13–16)',
      'The Davidic covenant (ch. 17)',
      'David\'s preparations for the temple (ch. 22–29)',
    ],
    structure: [
      { range: '1–9', title: 'Genealogies' },
      { range: '10–21', title: 'David\'s reign' },
      { range: '22–29', title: 'Preparing for the temple' },
    ],
  },
  {
    id: '2-chronicles',
    name: '2 Chronicles',
    testament: 'OT',
    bollsBook: 14,
    chapters: 36,
    author: 'Traditionally Ezra',
    date: 'c. 450–400 BC',
    audience: 'The returned exiles rebuilding Jerusalem',
    purpose: 'To show that blessing follows seeking God and ruin follows forsaking Him, urging faithfulness in the restored community.',
    overview:
      'Second Chronicles covers Solomon\'s reign — the temple\'s construction and dedication — then follows Judah\'s kings from Rehoboam to Zedekiah. Good kings who seek God (Asa, Jehoshaphat, Hezekiah, Josiah) bring blessing; wicked ones bring judgment. The book ends with the exile and Cyrus\'s decree allowing the Jews to return.',
    themes: ['Seeking God', 'Worship and the temple', 'Blessing and judgment', 'Repentance', 'God\'s faithfulness'],
    keyPeople: ['Solomon', 'Rehoboam', 'Asa', 'Jehoshaphat', 'Hezekiah', 'Manasseh', 'Josiah', 'Cyrus'],
    keyEvents: [
      'The temple built (ch. 3–5)',
      'Solomon\'s prayer and God\'s glory fills the temple (ch. 6–7)',
      'The division of the kingdom (ch. 10)',
      'Jehoshaphat\'s reforms (ch. 17–20)',
      'Hezekiah\'s Passover (ch. 30)',
      'Josiah\'s reforms (ch. 34–35)',
      'Cyrus\'s decree (ch. 36)',
    ],
    structure: [
      { range: '1–9', title: 'The reign of Solomon' },
      { range: '10–36', title: 'The kings of Judah to the exile and Cyrus\'s decree' },
    ],
  },
  {
    id: 'ezra',
    name: 'Ezra',
    testament: 'OT',
    bollsBook: 15,
    chapters: 10,
    author: 'Traditionally Ezra',
    date: 'c. 450–400 BC',
    audience: 'The returned exiles',
    purpose: 'To record God\'s faithfulness in bringing His people back from exile and rebuilding the temple.',
    overview:
      'Ezra tells of the first two waves of Jewish return from Babylon under Cyrus\'s decree. Zerubbabel leads the rebuilding of the temple despite opposition, and later Ezra the scribe arrives to teach the Law and call the people back to covenant faithfulness — including a painful reckoning over marriages to foreign wives.',
    themes: ['Restoration', 'God\'s sovereignty over kings', 'Worship restored', 'The Word of God', 'Repentance'],
    keyPeople: ['Zerubbabel', 'Ezra', 'Cyrus', 'Darius', 'Jeshua', 'Haggai', 'Zechariah'],
    keyEvents: [
      'Cyrus\'s decree (ch. 1)',
      'The altar rebuilt (ch. 3)',
      'Opposition to the work (ch. 4)',
      'The temple completed (ch. 6)',
      'Ezra arrives in Jerusalem (ch. 7)',
      'Repentance over intermarriage (ch. 9–10)',
    ],
    structure: [
      { range: '1–6', title: 'The first return: rebuilding the temple' },
      { range: '7–10', title: 'The second return: Ezra\'s reforms' },
    ],
  },
  {
    id: 'nehemiah',
    name: 'Nehemiah',
    testament: 'OT',
    bollsBook: 16,
    chapters: 13,
    author: 'Traditionally Nehemiah (with Ezra)',
    date: 'c. 430 BC',
    audience: 'The returned exiles',
    purpose: 'To show God rebuilding His people — walls, worship, and covenant — through a leader of prayer and resolve.',
    overview:
      'Nehemiah, cupbearer to the Persian king, receives permission to rebuild Jerusalem\'s ruined walls. Despite mockery, threats, and internal exploitation, the wall rises in 52 days. Ezra then reads the Law to the people, sparking revival, confession, and a renewed covenant. Nehemiah closes with further reforms.',
    themes: ['Prayer and action', 'Leadership', 'Perseverance under opposition', 'Revival', 'Covenant renewal'],
    keyPeople: ['Nehemiah', 'Ezra', 'Sanballat', 'Tobiah', 'Artaxerxes', 'Eliashib'],
    keyEvents: [
      'Nehemiah\'s prayer for Jerusalem (ch. 1)',
      'The king grants his request (ch. 2)',
      'The wall rebuilt in 52 days (ch. 6)',
      'Ezra reads the Law (ch. 8)',
      'National confession and covenant (ch. 9–10)',
      'Nehemiah\'s reforms (ch. 13)',
    ],
    structure: [
      { range: '1–7', title: 'Rebuilding the wall' },
      { range: '8–10', title: 'Revival under the Word' },
      { range: '11–13', title: 'Repopulating and reforming Jerusalem' },
    ],
  },
  {
    id: 'esther',
    name: 'Esther',
    testament: 'OT',
    bollsBook: 17,
    chapters: 10,
    author: 'Unknown (a Jewish writer in Persia)',
    date: 'c. 460–400 BC',
    audience: 'Jews living under Persian rule',
    purpose: 'To show God\'s hidden providence preserving His people — and to ground the feast of Purim.',
    overview:
      'Esther, a Jewish orphan, becomes queen of Persia just as the villain Haman plots to exterminate the Jews. With Mordecai\'s urging — "who knows whether you have come to the kingdom for such a time as this?" — she risks her life to expose the plot. The Jews are saved, Haman is hanged on his own gallows, and the feast of Purim is established.',
    themes: ['Providence', 'Courage', 'Reversal', 'God\'s hidden hand', 'Deliverance'],
    keyPeople: ['Esther', 'Mordecai', 'Haman', 'Ahasuerus (Xerxes)', 'Vashti'],
    keyEvents: [
      'Esther becomes queen (ch. 2)',
      'Haman\'s plot to destroy the Jews (ch. 3)',
      '"For such a time as this" (ch. 4)',
      'Esther\'s banquets (ch. 5, 7)',
      'Haman hanged (ch. 7)',
      'The feast of Purim (ch. 9)',
    ],
    structure: [
      { range: '1–4', title: 'Threat: Haman\'s decree' },
      { range: '5–8', title: 'Intervention: Esther\'s courage' },
      { range: '9–10', title: 'Triumph: Purim established' },
    ],
  },
];

BOOKS.push(
  {
    id: 'job',
    name: 'Job',
    testament: 'OT',
    bollsBook: 18,
    chapters: 42,
    author: 'Unknown (possibly Moses or an early patriarchal writer)',
    date: 'Possibly patriarchal era; written c. 1000–500 BC',
    audience: 'All who suffer and ask why',
    purpose: 'To wrestle with the mystery of suffering and show that God is worthy of trust even when His ways are hidden.',
    overview:
      'Job, a righteous man, loses everything — children, wealth, health — in a single day, and his friends insist he must have sinned. Through long poetic dialogues Job demands an answer, and God responds not with explanations but with a vision of His own majesty. Job repents in dust and ashes, and God restores him. It is the Bible\'s deepest treatment of innocent suffering.',
    themes: ['Suffering', 'The sovereignty of God', 'Faith tested', 'False comfort', 'Trust without answers'],
    keyPeople: ['Job', 'Eliphaz', 'Bildad', 'Zophar', 'Elihu', 'Satan', 'Job\'s wife'],
    keyEvents: [
      'Satan\'s challenge in heaven (ch. 1–2)',
      'Job\'s calamities (ch. 1–2)',
      'The friends\' accusations (ch. 4–31)',
      'Elihu\'s speeches (ch. 32–37)',
      'God answers from the whirlwind (ch. 38–41)',
      'Job\'s repentance and restoration (ch. 42)',
    ],
    structure: [
      { range: '1–2', title: 'Prologue: the test' },
      { range: '3–31', title: 'Dialogues with the friends' },
      { range: '32–37', title: 'Elihu speaks' },
      { range: '38–42', title: 'God answers; Job restored' },
    ],
  },
  {
    id: 'psalms',
    name: 'Psalms',
    testament: 'OT',
    bollsBook: 19,
    chapters: 150,
    author: 'David (73 psalms) and others: Asaph, sons of Korah, Solomon, Moses, Ethan, Heman',
    date: 'c. 1010–970 BC (David) through the exile',
    audience: 'Israel in worship — and all God\'s people ever since',
    purpose: 'To give God\'s people a prayer book and hymnal expressing every human emotion honestly before God.',
    overview:
      'The Psalms are 150 songs and prayers covering lament, praise, thanksgiving, confession, and trust. They teach us to bring our whole selves — joy and despair, anger and hope — to God. Quoted more than any other Old Testament book in the New Testament, they also point forward to the Messiah, especially the suffering and reigning King of Psalms 2, 22, and 110.',
    themes: ['Praise', 'Lament', 'Trust', 'Repentance', 'The Messiah', 'God\'s kingship'],
    keyPeople: ['David', 'Asaph', 'The sons of Korah', 'Solomon', 'Moses'],
    keyEvents: [
      'The blessed man and the wicked (Ps. 1)',
      'The shepherd\'s song (Ps. 23)',
      'The suffering servant\'s cry (Ps. 22)',
      'David\'s confession (Ps. 51)',
      'The songs of ascent (Ps. 120–134)',
      'The great Hallelujah chorus (Ps. 146–150)',
    ],
    structure: [
      { range: '1–41', title: 'Book 1: the way of the righteous' },
      { range: '42–72', title: 'Book 2: God our refuge' },
      { range: '73–89', title: 'Book 3: the holiness of God' },
      { range: '90–106', title: 'Book 4: God our King' },
      { range: '107–150', title: 'Book 5: praise and the pilgrimage' },
    ],
  },
  {
    id: 'proverbs',
    name: 'Proverbs',
    testament: 'OT',
    bollsBook: 20,
    chapters: 31,
    author: 'Solomon (mostly), with Agur, Lemuel, and others',
    date: 'c. 970–930 BC (Solomon\'s reign)',
    audience: 'The young — and all who seek wisdom',
    purpose: 'To teach practical wisdom: how to live skillfully and righteously in God\'s world, beginning with the fear of the LORD.',
    overview:
      'Proverbs is a collection of wise sayings contrasting the wise and the fool, the righteous and the wicked. Its foundation is "the fear of the LORD is the beginning of wisdom." Covering speech, work, money, friendship, and family, it shows that godliness is not abstract but lived out in everyday choices.',
    themes: ['Wisdom', 'The fear of the LORD', 'Discipline', 'Integrity', 'Speech', 'Diligence'],
    keyPeople: ['Solomon', 'Agur', 'Lemuel', 'The wise', 'The fool', 'The virtuous woman'],
    keyEvents: [
      'The call of wisdom (ch. 1, 8–9)',
      'Trust in the LORD (ch. 3)',
      'The contrast of wisdom and folly (ch. 9)',
      'Sayings of the wise (ch. 22–24)',
      'The words of Agur (ch. 30)',
      'The virtuous woman (ch. 31)',
    ],
    structure: [
      { range: '1–9', title: 'The father\'s appeal to seek wisdom' },
      { range: '10–24', title: 'Proverbs of Solomon' },
      { range: '25–29', title: 'Proverbs collected by Hezekiah\'s men' },
      { range: '30–31', title: 'Sayings of Agur and Lemuel' },
    ],
  },
  {
    id: 'ecclesiastes',
    name: 'Ecclesiastes',
    testament: 'OT',
    bollsBook: 21,
    chapters: 12,
    author: 'Traditionally Solomon ("the Preacher")',
    date: 'c. 935 BC',
    audience: 'Those tempted to find meaning in life apart from God',
    purpose: 'To expose the emptiness of life "under the sun" and point to fearing God as life\'s true meaning.',
    overview:
      'Ecclesiastes is the searching memoir of the Preacher, who tests pleasure, wealth, work, and wisdom and finds them all "vanity" — a vapor — apart from God. The book\'s famous poem on the seasons of life (ch. 3) and its conclusion — "Fear God and keep his commandments" — give this honest book its hopeful landing.',
    themes: ['Vanity', 'The meaning of life', 'Time and mortality', 'The fear of God', 'Contentment'],
    keyPeople: ['The Preacher (Solomon)', 'The wise', 'The fool'],
    keyEvents: [
      'The experiment with pleasure and wealth (ch. 2)',
      'A time for everything (ch. 3)',
      'The value of companionship (ch. 4)',
      'Remember your Creator in youth (ch. 12)',
      'The conclusion: fear God (ch. 12)',
    ],
    structure: [
      { range: '1–2', title: 'The problem: all is vanity' },
      { range: '3–11', title: 'Searching for meaning' },
      { range: '12', title: 'The conclusion: fear God' },
    ],
  },
  {
    id: 'song-of-solomon',
    name: 'Song of Solomon',
    testament: 'OT',
    bollsBook: 22,
    chapters: 8,
    author: 'Solomon',
    date: 'c. 970–930 BC',
    audience: 'Married couples and all who love',
    purpose: 'To celebrate the beauty and exclusivity of married love as God\'s good gift — and as a picture of Christ\'s love for the church.',
    overview:
      'The Song of Solomon is a lyrical dialogue between a bride and bridegroom, celebrating romantic love in vivid poetry. It honors marriage as God designed it — passionate, exclusive, and joyful. Many have also read it as an allegory of the love between Christ and His people.',
    themes: ['Married love', 'Beauty', 'Exclusivity', 'Longing', 'Christ and the church'],
    keyPeople: ['Solomon', 'The Shulammite bride', 'The daughters of Jerusalem'],
    keyEvents: [
      'The bride\'s longing (ch. 1)',
      'The lovers\' admiration (ch. 2–4)',
      'The search for the beloved (ch. 5)',
      'The garden of love (ch. 6–7)',
      '"Love is strong as death" (ch. 8)',
    ],
    structure: [
      { range: '1–3', title: 'Longing and union' },
      { range: '4–5', title: 'Admiration and separation' },
      { range: '6–8', title: 'Reunion and the triumph of love' },
    ],
  },
  {
    id: 'isaiah',
    name: 'Isaiah',
    testament: 'OT',
    bollsBook: 23,
    chapters: 66,
    author: 'Isaiah, son of Amoz',
    date: 'c. 740–680 BC',
    audience: 'Judah and Jerusalem, facing Assyrian threat',
    purpose: 'To warn of judgment for sin and to unveil the coming Servant and the future glory of God\'s kingdom.',
    overview:
      'Isaiah is the towering prophet of the Old Testament. He warns Judah of coming judgment, comforts the exiles with promises of restoration, and — most remarkably — paints the clearest Old Testament portrait of the Messiah: the virgin-born child (ch. 7), the Prince of Peace (ch. 9), and the suffering Servant who bears our sins (ch. 53).',
    themes: ['The holiness of God', 'Judgment and salvation', 'The Messiah', 'The suffering Servant', 'The new creation'],
    keyPeople: ['Isaiah', 'Ahaz', 'Hezekiah', 'Cyrus', 'The suffering Servant'],
    keyEvents: [
      'Isaiah\'s vision and call (ch. 6)',
      'The sign of Immanuel (ch. 7)',
      'The Prince of Peace foretold (ch. 9)',
      'Hezekiah\'s deliverance (ch. 36–37)',
      'The suffering Servant (ch. 53)',
      'The new heavens and new earth (ch. 65–66)',
    ],
    structure: [
      { range: '1–35', title: 'Prophecies of judgment' },
      { range: '36–39', title: 'Historical interlude: Hezekiah' },
      { range: '40–55', title: 'Comfort: the Servant and salvation' },
      { range: '56–66', title: 'The future glory of Zion' },
    ],
  },
  {
    id: 'jeremiah',
    name: 'Jeremiah',
    testament: 'OT',
    bollsBook: 24,
    chapters: 52,
    author: 'Jeremiah',
    date: 'c. 627–586 BC',
    audience: 'Judah in its final decades before the Babylonian exile',
    purpose: 'To call Judah to repentance before judgment falls — and to promise a new covenant after it.',
    overview:
      'Jeremiah, the "weeping prophet," preached for 40 years to a nation that would not listen. He warned of Babylon\'s coming judgment, endured persecution and imprisonment, and watched Jerusalem fall. Yet amid the tears he gave the Bible\'s clearest promise of the new covenant (ch. 31), when God would write His law on human hearts.',
    themes: ['Judgment', 'The new covenant', 'Repentance', 'The weeping prophet', 'God\'s faithfulness'],
    keyPeople: ['Jeremiah', 'Baruch', 'Zedekiah', 'Nebuchadnezzar', 'Hananiah'],
    keyEvents: [
      'Jeremiah\'s call (ch. 1)',
      'The temple sermon (ch. 7)',
      'The potter and the clay (ch. 18)',
      'The new covenant promised (ch. 31)',
      'The purchase of the field (ch. 32)',
      'The fall of Jerusalem (ch. 39, 52)',
    ],
    structure: [
      { range: '1–25', title: 'Prophecies against Judah' },
      { range: '26–45', title: 'Jeremiah\'s sufferings and messages' },
      { range: '46–51', title: 'Prophecies against the nations' },
      { range: '52', title: 'The fall of Jerusalem' },
    ],
  },
  {
    id: 'lamentations',
    name: 'Lamentations',
    testament: 'OT',
    bollsBook: 25,
    chapters: 5,
    author: 'Traditionally Jeremiah',
    date: 'c. 586 BC (after Jerusalem\'s fall)',
    audience: 'The survivors of Jerusalem\'s destruction',
    purpose: 'To mourn Jerusalem\'s fall honestly while clinging to hope in God\'s unfailing mercies.',
    overview:
      'Lamentations is five funeral poems over the ruins of Jerusalem. The prophet weeps over the city\'s desolation as the wages of sin, confesses God\'s justice, and — in the book\'s luminous center — declares, "Great is thy faithfulness... his mercies are new every morning." Grief and hope sit side by side.',
    themes: ['Grief', 'God\'s justice', 'Hope in suffering', 'Confession', 'Faithfulness of God'],
    keyPeople: ['Jeremiah', 'The daughter of Zion'],
    keyEvents: [
      'The desolation of the city (ch. 1)',
      'God\'s anger poured out (ch. 2)',
      '"Great is thy faithfulness" (ch. 3)',
      'The punishment of sin (ch. 4)',
      'A prayer for restoration (ch. 5)',
    ],
    structure: [
      { range: '1', title: 'The city weeps' },
      { range: '2', title: 'The LORD has done it' },
      { range: '3', title: 'Hope in affliction' },
      { range: '4', title: 'The price of sin' },
      { range: '5', title: 'Restore us, O LORD' },
    ],
  },
  {
    id: 'ezekiel',
    name: 'Ezekiel',
    testament: 'OT',
    bollsBook: 26,
    chapters: 48,
    author: 'Ezekiel, son of Buzi',
    date: 'c. 593–571 BC',
    audience: 'The Jewish exiles in Babylon',
    purpose: 'To explain the exile as God\'s judgment and to promise restoration through a new heart and a new temple.',
    overview:
      'Ezekiel, a priest-turned-prophet among the exiles, saw stunning visions: God\'s glory departing the temple, the valley of dry bones coming to life, and a new temple where God\'s glory returns. He acted out his prophecies in vivid street theater. His promise of a new heart and God\'s Spirit (ch. 36) became central to New Testament hope.',
    themes: ['The glory of God', 'Judgment', 'Restoration', 'The new heart', 'The valley of dry bones'],
    keyPeople: ['Ezekiel', 'Zedekiah', 'Nebuchadnezzar', 'The prince'],
    keyEvents: [
      'The vision of God\'s glory (ch. 1)',
      'The glory departs the temple (ch. 10–11)',
      'The valley of dry bones (ch. 37)',
      'The promise of a new heart (ch. 36)',
      'Gog and Magog (ch. 38–39)',
      'The vision of the new temple (ch. 40–48)',
    ],
    structure: [
      { range: '1–24', title: 'Judgment on Jerusalem' },
      { range: '25–32', title: 'Judgment on the nations' },
      { range: '33–39', title: 'Promises of restoration' },
      { range: '40–48', title: 'The new temple and land' },
    ],
  },
  {
    id: 'daniel',
    name: 'Daniel',
    testament: 'OT',
    bollsBook: 27,
    chapters: 12,
    author: 'Daniel',
    date: 'c. 605–536 BC (during the Babylonian and Persian empires)',
    audience: 'The exiles — and all God\'s people under earthly powers',
    purpose: 'To show that God rules over the kingdoms of men, and to give hope of His everlasting kingdom.',
    overview:
      'Daniel follows a young Jewish exile who rises to high office in Babylon and Persia through integrity and God-given wisdom. The fiery furnace and the lions\' den display God\'s power to save. The second half records apocalyptic visions of coming kingdoms and the Son of Man receiving an everlasting dominion.',
    themes: ['God\'s sovereignty', 'Faithfulness in exile', 'The kingdom of God', 'Prophecy', 'Courage'],
    keyPeople: ['Daniel', 'Nebuchadnezzar', 'Belshazzar', 'Darius', 'Shadrach, Meshach, Abednego', 'Gabriel'],
    keyEvents: [
      'Daniel\'s resolve in Babylon (ch. 1)',
      'Nebuchadnezzar\'s dream (ch. 2)',
      'The fiery furnace (ch. 3)',
      'The handwriting on the wall (ch. 5)',
      'Daniel in the lions\' den (ch. 6)',
      'The vision of the Son of Man (ch. 7)',
      'The seventy weeks (ch. 9)',
    ],
    structure: [
      { range: '1–6', title: 'Daniel in the courts of kings' },
      { range: '7–12', title: 'Visions of the coming kingdom' },
    ],
  },
  {
    id: 'hosea',
    name: 'Hosea',
    testament: 'OT',
    bollsBook: 28,
    chapters: 14,
    author: 'Hosea, son of Beeri',
    date: 'c. 750–722 BC',
    audience: 'The northern kingdom of Israel',
    purpose: 'To portray God\'s faithful love for an unfaithful people through the prophet\'s own painful marriage.',
    overview:
      'God told Hosea to marry Gomer, an unfaithful wife, as a living picture of Israel\'s spiritual adultery with idols. Though betrayed again and again, Hosea buys his wife back — just as God keeps pursuing His people. It is one of Scripture\'s most moving portraits of redeeming love.',
    themes: ['God\'s steadfast love', 'Spiritual adultery', 'Repentance', 'Redemption', 'Knowledge of God'],
    keyPeople: ['Hosea', 'Gomer', 'Jeroboam II'],
    keyEvents: [
      'Hosea marries Gomer (ch. 1)',
      'Israel\'s unfaithfulness exposed (ch. 2–3)',
      'God\'s controversy with Israel (ch. 4)',
      'The call to return (ch. 14)',
    ],
    structure: [
      { range: '1–3', title: 'The prophet\'s marriage: a parable' },
      { range: '4–14', title: 'God\'s charge and promise to Israel' },
    ],
  },
  {
    id: 'joel',
    name: 'Joel',
    testament: 'OT',
    bollsBook: 29,
    chapters: 3,
    author: 'Joel, son of Pethuel',
    date: 'Possibly 9th century BC',
    audience: 'Judah and Jerusalem',
    purpose: 'To call God\'s people to repentance in view of the coming "day of the LORD" — and to promise the Spirit.',
    overview:
      'A devastating locust plague becomes Joel\'s picture of the coming day of the LORD. He calls the nation to rend their hearts, not their garments, and promises that God will restore the years the locusts have eaten. His prophecy of God pouring out His Spirit on all flesh was fulfilled at Pentecost.',
    themes: ['The day of the LORD', 'Repentance', 'The outpouring of the Spirit', 'Restoration'],
    keyPeople: ['Joel', 'The priests'],
    keyEvents: [
      'The locust plague (ch. 1)',
      'The call to repentance (ch. 2)',
      'The promise of the Spirit (ch. 2)',
      'Judgment of the nations (ch. 3)',
    ],
    structure: [
      { range: '1', title: 'The plague and the call to lament' },
      { range: '2', title: 'Repentance and the promised Spirit' },
      { range: '3', title: 'Judgment and blessing' },
    ],
  },
  {
    id: 'amos',
    name: 'Amos',
    testament: 'OT',
    bollsBook: 30,
    chapters: 9,
    author: 'Amos, a shepherd from Tekoa',
    date: 'c. 760–750 BC',
    audience: 'The northern kingdom of Israel in prosperity',
    purpose: 'To denounce empty religion and social injustice, calling for justice to "roll down like waters."',
    overview:
      'Amos was a shepherd and fig-picker, not a professional prophet, whom God sent from Judah to confront Israel\'s wealthy elite. He condemned their exploitation of the poor, their corrupt courts, and their hollow worship. His famous cry — "let justice roll down like waters" — still echoes in movements for justice today.',
    themes: ['Justice', 'True worship', 'Judgment', 'Social righteousness', 'The remnant'],
    keyPeople: ['Amos', 'Jeroboam II', 'Amaziah the priest'],
    keyEvents: [
      'Judgment on the nations and Israel (ch. 1–2)',
      '"Prepare to meet your God" (ch. 4)',
      'The call for justice (ch. 5)',
      'The plumb line vision (ch. 7)',
      'The restoration of David\'s house (ch. 9)',
    ],
    structure: [
      { range: '1–2', title: 'Judgments on the nations' },
      { range: '3–6', title: 'Judgments on Israel' },
      { range: '7–9', title: 'Visions and the promise of restoration' },
    ],
  },
  {
    id: 'obadiah',
    name: 'Obadiah',
    testament: 'OT',
    bollsBook: 31,
    chapters: 1,
    author: 'Obadiah',
    date: 'c. 586 BC (after Jerusalem\'s fall)',
    audience: 'Edom — and all who gloat over God\'s people',
    purpose: 'To pronounce judgment on Edom for betraying Judah, affirming that God defends His people.',
    overview:
      'The shortest book in the Old Testament is a single prophecy against Edom, Judah\'s brother-nation, which gloated over Jerusalem\'s destruction and helped plunder it. Obadiah declares Edom\'s pride will be its ruin and ends with the promise: "the kingdom shall be the LORD\'s."',
    themes: ['Pride', 'Judgment', 'God\'s justice', 'The kingdom of the LORD'],
    keyPeople: ['Obadiah'],
    keyEvents: [
      'The vision against Edom (v. 1–9)',
      'Edom\'s violence against Judah (v. 10–14)',
      'The day of the LORD (v. 15–21)',
    ],
    structure: [{ range: '1–21', title: 'The doom of Edom; the triumph of Zion' }],
  },
  {
    id: 'jonah',
    name: 'Jonah',
    testament: 'OT',
    bollsBook: 32,
    chapters: 4,
    author: 'Traditionally Jonah, son of Amittai',
    date: 'c. 760 BC',
    audience: 'Israel — and all who resist God\'s mercy to outsiders',
    purpose: 'To show that God\'s compassion extends to the nations, exposing the prophet\'s own lack of mercy.',
    overview:
      'Jonah flees God\'s call to preach to Nineveh, Israel\'s cruel enemy. Swallowed by a great fish, he prays and is delivered, then preaches — and the whole city repents. Instead of rejoicing, Jonah sulks. God\'s closing question — should He not pity the great city? — leaves the reader to answer.',
    themes: ['God\'s mercy to the nations', 'Repentance', 'Disobedience', 'Compassion'],
    keyPeople: ['Jonah', 'The sailors', 'The king of Nineveh'],
    keyEvents: [
      'Jonah flees to Tarshish (ch. 1)',
      'The great fish (ch. 1–2)',
      'Jonah\'s prayer (ch. 2)',
      'Nineveh repents (ch. 3)',
      'Jonah\'s anger and God\'s lesson (ch. 4)',
    ],
    structure: [
      { range: '1–2', title: 'Jonah flees; God pursues' },
      { range: '3', title: 'Jonah preaches; Nineveh repents' },
      { range: '4', title: 'Jonah sulks; God teaches' },
    ],
  },
  {
    id: 'micah',
    name: 'Micah',
    testament: 'OT',
    bollsBook: 33,
    chapters: 7,
    author: 'Micah of Moresheth',
    date: 'c. 735–700 BC',
    audience: 'Judah and Israel',
    purpose: 'To denounce injustice and idolatry, and to promise a coming Ruler from Bethlehem.',
    overview:
      'Micah, a contemporary of Isaiah, preached against corrupt leaders, false prophets, and the wealthy who crushed the poor. He gave the Bible\'s most famous summary of true religion — "do justly, love mercy, and walk humbly with your God" — and foretold that a Ruler would come from little Bethlehem.',
    themes: ['Justice', 'The Messiah from Bethlehem', 'Judgment and restoration', 'True religion'],
    keyPeople: ['Micah', 'Hezekiah'],
    keyEvents: [
      'Judgment on Samaria and Jerusalem (ch. 1)',
      'Woe to the oppressors (ch. 2)',
      '"Do justly, love mercy" (ch. 6)',
      'The Ruler from Bethlehem (ch. 5)',
      'The LORD\'s pardon (ch. 7)',
    ],
    structure: [
      { range: '1–3', title: 'Judgment announced' },
      { range: '4–5', title: 'The coming kingdom and King' },
      { range: '6–7', title: 'The LORD\'s case and mercy' },
    ],
  },
  {
    id: 'nahum',
    name: 'Nahum',
    testament: 'OT',
    bollsBook: 34,
    chapters: 3,
    author: 'Nahum of Elkosh',
    date: 'c. 663–612 BC',
    audience: 'Judah, oppressed by Assyria',
    purpose: 'To announce the fall of Nineveh, showing God judges proud empires and comforts His people.',
    overview:
      'A century after Jonah\'s Nineveh repented, the city returned to cruelty — and Nahum prophesies its doom. Where Jonah showed God\'s mercy to a repentant city, Nahum shows His justice against an unrepentant one. The book comforts the oppressed: God will not let evil have the last word.',
    themes: ['God\'s justice', 'The fall of the proud', 'Comfort for the oppressed', 'The wrath of God'],
    keyPeople: ['Nahum'],
    keyEvents: [
      'The character of God: jealous yet good (ch. 1)',
      'The siege of Nineveh described (ch. 2)',
      'The reasons for Nineveh\'s fall (ch. 3)',
    ],
    structure: [
      { range: '1', title: 'God the avenger' },
      { range: '2', title: 'Nineveh besieged' },
      { range: '3', title: 'Nineveh\'s guilt and doom' },
    ],
  },
  {
    id: 'habakkuk',
    name: 'Habakkuk',
    testament: 'OT',
    bollsBook: 35,
    chapters: 3,
    author: 'Habakkuk',
    date: 'c. 605 BC',
    audience: 'Judah, watching Babylon rise',
    purpose: 'To wrestle honestly with God\'s ways and learn to live by faith when nothing makes sense.',
    overview:
      'Habakkuk is a dialogue between the prophet and God: Why does evil go unpunished? How can God use wicked Babylon to judge Judah? God\'s answer — "the just shall live by his faith" — became a cornerstone of Paul\'s gospel. The book ends with one of Scripture\'s greatest songs of trust in the midst of ruin.',
    themes: ['Faith', 'God\'s sovereignty', 'Honest questioning', 'Joy in suffering'],
    keyPeople: ['Habakkuk'],
    keyEvents: [
      'Habakkuk\'s complaint (ch. 1)',
      '"The just shall live by faith" (ch. 2)',
      'Woes on the proud (ch. 2)',
      'Habakkuk\'s prayer and song of trust (ch. 3)',
    ],
    structure: [
      { range: '1', title: 'The prophet\'s complaint' },
      { range: '2', title: 'God\'s answer: live by faith' },
      { range: '3', title: 'A hymn of trust' },
    ],
  },
  {
    id: 'zephaniah',
    name: 'Zephaniah',
    testament: 'OT',
    bollsBook: 36,
    chapters: 3,
    author: 'Zephaniah, descendant of Hezekiah',
    date: 'c. 640–621 BC (during Josiah\'s reign)',
    audience: 'Judah before Josiah\'s reforms',
    purpose: 'To warn of the coming day of the LORD and to promise joy to the humble remnant.',
    overview:
      'Zephaniah, of royal blood, preached during Josiah\'s reign about the coming day of the LORD — a day of judgment on Judah and the nations. Yet the book ends with one of the Bible\'s most tender pictures of God: He rejoices over His people with singing and quiets them with His love.',
    themes: ['The day of the LORD', 'Judgment', 'The humble remnant', 'God\'s delight in His people'],
    keyPeople: ['Zephaniah', 'Josiah'],
    keyEvents: [
      'The coming day of wrath (ch. 1)',
      'Seek the LORD (ch. 2)',
      'Woe to rebellious Jerusalem (ch. 3)',
      'The LORD rejoices over His people (ch. 3)',
    ],
    structure: [
      { range: '1', title: 'The day of the LORD against Judah' },
      { range: '2', title: 'Judgment on the nations' },
      { range: '3', title: 'Jerusalem judged; the remnant restored' },
    ],
  },
  {
    id: 'haggai',
    name: 'Haggai',
    testament: 'OT',
    bollsBook: 37,
    chapters: 2,
    author: 'Haggai',
    date: '520 BC',
    audience: 'The returned exiles in Jerusalem',
    purpose: 'To rebuke spiritual apathy and stir the people to finish rebuilding the temple.',
    overview:
      'Sixteen years after the exiles returned, the temple still lay in ruins while the people built paneled houses for themselves. Haggai\'s four short sermons in 520 BC cut to the heart: "Consider your ways." The people obey, the work resumes, and God promises that the glory of this house will surpass the former.',
    themes: ['Priorities', 'Repentance', 'God\'s presence', 'Encouragement'],
    keyPeople: ['Haggai', 'Zerubbabel', 'Joshua the high priest', 'Darius'],
    keyEvents: [
      '"Consider your ways" (ch. 1)',
      'The people resume the work (ch. 1)',
      'The promise of greater glory (ch. 2)',
      'The signet ring: Zerubbabel chosen (ch. 2)',
    ],
    structure: [
      { range: '1', title: 'The call to rebuild' },
      { range: '2', title: 'Encouragement and promise' },
    ],
  },
  {
    id: 'zechariah',
    name: 'Zechariah',
    testament: 'OT',
    bollsBook: 38,
    chapters: 14,
    author: 'Zechariah, son of Berechiah',
    date: 'c. 520–480 BC',
    audience: 'The returned exiles rebuilding the temple',
    purpose: 'To encourage the builders with visions of God\'s presence and detailed prophecies of the coming Messiah.',
    overview:
      'Zechariah preached alongside Haggai, but his book looks far beyond the temple to the Messiah: the Branch, the humble King riding on a donkey, the Shepherd sold for thirty pieces of silver, and the pierced One whom they will mourn. His night visions assure the discouraged builders that God\'s Spirit, not human might, will finish the work.',
    themes: ['The Messiah', 'God\'s Spirit', 'Restoration', 'The coming King', 'Repentance'],
    keyPeople: ['Zechariah', 'Zerubbabel', 'Joshua the high priest'],
    keyEvents: [
      'The eight night visions (ch. 1–6)',
      '"Not by might, nor by power, but by my Spirit" (ch. 4)',
      'The crowning of Joshua: the Branch (ch. 6)',
      'The King on a donkey (ch. 9)',
      'The thirty pieces of silver (ch. 11)',
      'The pierced One (ch. 12)',
    ],
    structure: [
      { range: '1–8', title: 'Visions of encouragement' },
      { range: '9–14', title: 'The coming Messiah and His kingdom' },
    ],
  },
  {
    id: 'malachi',
    name: 'Malachi',
    testament: 'OT',
    bollsBook: 39,
    chapters: 4,
    author: 'Malachi',
    date: 'c. 430 BC',
    audience: 'The restored community in Jerusalem',
    purpose: 'To confront spiritual coldness and promise the coming Messenger — ending the Old Testament with hope.',
    overview:
      'Malachi is the last voice of the Old Testament, confronting a weary, cynical people: corrupt priests, broken marriages, withheld tithes. Yet he promises that the LORD will send His messenger to prepare the way, and that the Sun of Righteousness will rise. The Old Testament closes looking forward to John the Baptist and Christ.',
    themes: ['Covenant faithfulness', 'True worship', 'The coming Messenger', 'Judgment and hope'],
    keyPeople: ['Malachi', 'Elijah (to come)'],
    keyEvents: [
      'God\'s love for Jacob (ch. 1)',
      'Rebuke of the priests (ch. 1–2)',
      'The call to bring the tithe (ch. 3)',
      'The coming day of the LORD (ch. 4)',
      '"I will send Elijah" (ch. 4)',
    ],
    structure: [
      { range: '1–2', title: 'The LORD\'s complaints against Israel' },
      { range: '3–4', title: 'The coming Messenger and the day of the LORD' },
    ],
  }
);

BOOKS.push(
  {
    id: 'matthew',
    name: 'Matthew',
    testament: 'NT',
    bollsBook: 40,
    chapters: 28,
    author: 'Matthew (Levi), the tax collector and apostle',
    date: 'c. AD 60–65',
    audience: 'Jewish readers, showing Jesus as the promised Messiah-King',
    purpose: 'To prove that Jesus is the long-awaited King of the Jews and to record His teaching for disciples.',
    overview:
      'Matthew presents Jesus as the Messiah foretold in the Old Testament, opening with a genealogy linking Him to Abraham and David. Structured around five great teaching blocks — including the Sermon on the Mount — it traces Jesus\' ministry, death, and resurrection, closing with the Great Commission to make disciples of all nations.',
    themes: ['Jesus as King', 'The kingdom of heaven', 'Fulfilled prophecy', 'Discipleship', 'Righteousness'],
    keyPeople: ['Jesus', 'Mary', 'Joseph', 'John the Baptist', 'Peter', 'The twelve apostles'],
    keyEvents: [
      'The genealogy and birth of Jesus (ch. 1–2)',
      'The Sermon on the Mount (ch. 5–7)',
      'Peter\'s confession (ch. 16)',
      'The Transfiguration (ch. 17)',
      'The Olivet Discourse (ch. 24–25)',
      'The crucifixion and resurrection (ch. 27–28)',
      'The Great Commission (ch. 28)',
    ],
    structure: [
      { range: '1–4', title: 'The King\'s arrival' },
      { range: '5–7', title: 'The Sermon on the Mount' },
      { range: '8–25', title: 'The King\'s ministry and teaching' },
      { range: '26–28', title: 'The King\'s death, resurrection, and commission' },
    ],
  },
  {
    id: 'mark',
    name: 'Mark',
    testament: 'NT',
    bollsBook: 41,
    chapters: 16,
    author: 'John Mark, companion of Peter',
    date: 'c. AD 55–65',
    audience: 'Roman/Gentile Christians',
    purpose: 'To present Jesus as the suffering Servant-Son of God who came to give His life as a ransom.',
    overview:
      'Mark is the shortest, fastest-moving Gospel — "immediately" is its favorite word. It shows Jesus in constant action: teaching, healing, casting out demons, calming storms. The turning point comes at Peter\'s confession, after which Jesus sets His face toward the cross, revealing that true greatness is found in serving.',
    themes: ['The Servant of God', 'Action', 'The cross', 'Discipleship', 'The Son of God'],
    keyPeople: ['Jesus', 'Peter', 'James', 'John', 'John the Baptist', 'The twelve'],
    keyEvents: [
      'Jesus\' baptism and temptation (ch. 1)',
      'The calling of the disciples (ch. 1–3)',
      'Parables of the kingdom (ch. 4)',
      'Peter\'s confession (ch. 8)',
      'The Transfiguration (ch. 9)',
      'The crucifixion and resurrection (ch. 15–16)',
    ],
    structure: [
      { range: '1–8', title: 'The Servant\'s ministry in Galilee' },
      { range: '9–10', title: 'The road to the cross' },
      { range: '11–16', title: 'The Servant in Jerusalem: death and resurrection' },
    ],
  },
  {
    id: 'luke',
    name: 'Luke',
    testament: 'NT',
    bollsBook: 42,
    chapters: 24,
    author: 'Luke, the beloved physician and companion of Paul',
    date: 'c. AD 60–62',
    audience: 'Theophilus and Gentile Christians',
    purpose: 'To give an orderly, carefully researched account of Jesus\' life, emphasizing His compassion for the outcast.',
    overview:
      'Luke, the only Gentile Gospel writer, stresses that Jesus came for all people — Samaritans, tax collectors, women, the poor, and sinners. With beloved parables like the Good Samaritan and the Prodigal Son, and the most detailed Christmas story, Luke shows the Savior whose heart runs toward the lost. The book ends with the ascension and leads into Acts.',
    themes: ['Compassion for the lost', 'Prayer', 'The Holy Spirit', 'Joy', 'Salvation for all'],
    keyPeople: ['Jesus', 'Mary', 'Elizabeth', 'Zechariah', 'John the Baptist', 'The twelve', 'Martha and Mary'],
    keyEvents: [
      'The annunciation and birth of Jesus (ch. 1–2)',
      'Jesus\' baptism and genealogy (ch. 3)',
      'The Sermon on the Plain (ch. 6)',
      'The parables of the lost (ch. 15)',
      'The road to Emmaus (ch. 24)',
      'The ascension (ch. 24)',
    ],
    structure: [
      { range: '1–2', title: 'The birth of the Savior' },
      { range: '3–9', title: 'The ministry in Galilee' },
      { range: '10–19', title: 'The journey to Jerusalem' },
      { range: '20–24', title: 'Death, resurrection, and ascension' },
    ],
  },
  {
    id: 'john',
    name: 'John',
    testament: 'NT',
    bollsBook: 43,
    chapters: 21,
    author: 'John the apostle, "the disciple whom Jesus loved"',
    date: 'c. AD 85–95',
    audience: 'All who need to believe — Jew and Gentile',
    purpose: 'To prove Jesus is the Son of God, so that readers may believe and have eternal life.',
    overview:
      'John\'s Gospel is the most theological, opening with the majestic prologue: the Word was God and became flesh. Built around seven signs and seven "I am" sayings, it shows Jesus as the divine Son — the Bread of Life, the Light of the World, the Good Shepherd, the Resurrection. Its purpose is stated plainly: "that you may believe."',
    themes: ['The deity of Christ', 'Belief and eternal life', 'The "I am" sayings', 'Love', 'The Holy Spirit'],
    keyPeople: ['Jesus', 'John the Baptist', 'Nicodemus', 'The Samaritan woman', 'Martha, Mary, and Lazarus', 'Peter', 'Thomas'],
    keyEvents: [
      'The Word became flesh (ch. 1)',
      'The wedding at Cana (ch. 2)',
      'Nicodemus and the new birth (ch. 3)',
      'The woman at the well (ch. 4)',
      'The raising of Lazarus (ch. 11)',
      'The Last Supper discourses (ch. 13–17)',
      'The crucifixion and resurrection (ch. 19–20)',
    ],
    structure: [
      { range: '1', title: 'Prologue: the Word' },
      { range: '2–12', title: 'The Book of Signs' },
      { range: '13–17', title: 'The farewell discourses' },
      { range: '18–21', title: 'The passion, resurrection, and epilogue' },
    ],
  },
  {
    id: 'acts',
    name: 'Acts',
    testament: 'NT',
    bollsBook: 44,
    chapters: 28,
    author: 'Luke',
    date: 'c. AD 62–63',
    audience: 'Theophilus and the early church',
    purpose: 'To record the birth and spread of the church through the power of the Holy Spirit.',
    overview:
      'Acts is the sequel to Luke\'s Gospel: the story of the church\'s explosive growth from Jerusalem to Rome. The Spirit falls at Pentecost, Peter preaches to Jews, Stephen is martyred, Saul is converted, and Paul carries the gospel across the Roman world. It ends with Paul preaching in Rome — the mission still unfinished, still ours.',
    themes: ['The Holy Spirit', 'The spread of the gospel', 'The church', 'Witness', 'Persecution and power'],
    keyPeople: ['Peter', 'Paul', 'Stephen', 'Philip', 'Barnabas', 'James', 'Lydia', 'Timothy'],
    keyEvents: [
      'The ascension (ch. 1)',
      'Pentecost (ch. 2)',
      'Stephen\'s martyrdom (ch. 7)',
      'Saul\'s conversion (ch. 9)',
      'Peter and Cornelius: the gospel to Gentiles (ch. 10)',
      'The Jerusalem council (ch. 15)',
      'Paul\'s missionary journeys (ch. 13–21)',
      'Paul in Rome (ch. 28)',
    ],
    structure: [
      { range: '1–7', title: 'The church in Jerusalem' },
      { range: '8–12', title: 'The church in Judea and Samaria' },
      { range: '13–28', title: 'The church to the ends of the earth' },
    ],
  },
  {
    id: 'romans',
    name: 'Romans',
    testament: 'NT',
    bollsBook: 45,
    chapters: 16,
    author: 'The apostle Paul',
    date: 'c. AD 57 (from Corinth)',
    audience: 'The Christians in Rome — Jew and Gentile',
    purpose: 'To set out the gospel systematically: righteousness from God through faith in Christ alone.',
    overview:
      'Romans is Paul\'s theological masterpiece — the most complete explanation of the gospel in the New Testament. All have sinned, but God justifies sinners through faith in Christ; believers are united with Him, freed from sin\'s power, and destined for glory. The final chapters apply the gospel to daily life and church unity.',
    themes: ['Justification by faith', 'Sin and grace', 'Union with Christ', 'The Holy Spirit', 'God\'s plan for Israel', 'Transformed living'],
    keyPeople: ['Paul', 'Abraham', 'Adam', 'Phoebe'],
    keyEvents: [
      '"The righteous shall live by faith" (ch. 1)',
      'All have sinned (ch. 3)',
      'Justification by faith (ch. 5)',
      'Dead to sin, alive in Christ (ch. 6)',
      'Life in the Spirit (ch. 8)',
      'The living sacrifice (ch. 12)',
    ],
    structure: [
      { range: '1–3', title: 'The need: all under sin' },
      { range: '4–5', title: 'Justification by faith' },
      { range: '6–8', title: 'Sanctification by the Spirit' },
      { range: '9–11', title: 'God\'s plan for Israel' },
      { range: '12–16', title: 'The gospel applied' },
    ],
  },
  {
    id: '1-corinthians',
    name: '1 Corinthians',
    testament: 'NT',
    bollsBook: 46,
    chapters: 16,
    author: 'The apostle Paul',
    date: 'c. AD 55 (from Ephesus)',
    audience: 'The church in Corinth',
    purpose: 'To correct division, immorality, and disorder in the church, grounding everything in the cross.',
    overview:
      'Paul wrote to a gifted but deeply troubled church in the morally corrupt city of Corinth. He addresses factions, sexual immorality, lawsuits, marriage, worship, spiritual gifts, and the resurrection — always pointing back to Christ crucified. The famous "love chapter" (ch. 13) sits at the heart of his teaching on gifts.',
    themes: ['Unity', 'The cross', 'Holiness', 'Love', 'Orderly worship', 'The resurrection'],
    keyPeople: ['Paul', 'Apollos', 'Cephas (Peter)', 'Timothy', 'Chloe\'s household'],
    keyEvents: [
      'The call to unity (ch. 1–4)',
      'Discipline for immorality (ch. 5)',
      'Teaching on marriage (ch. 7)',
      'The Lord\'s Supper (ch. 11)',
      'The love chapter (ch. 13)',
      'The resurrection chapter (ch. 15)',
    ],
    structure: [
      { range: '1–6', title: 'Divisions and disorders rebuked' },
      { range: '7–14', title: 'Questions answered: marriage, worship, gifts' },
      { range: '15–16', title: 'The resurrection and closing' },
    ],
  },
  {
    id: '2-corinthians',
    name: '2 Corinthians',
    testament: 'NT',
    bollsBook: 47,
    chapters: 13,
    author: 'The apostle Paul',
    date: 'c. AD 56 (from Macedonia)',
    audience: 'The church in Corinth',
    purpose: 'To defend Paul\'s apostolic ministry and teach that God\'s strength is perfected in weakness.',
    overview:
      'Second Corinthians is Paul\'s most personal letter, written after a painful visit and a severe letter to Corinth. He defends his ministry against false apostles, describes the new covenant\'s glory, urges generous giving, and boasts — paradoxically — in his weaknesses, having learned that Christ\'s power rests on the weak.',
    themes: ['Strength in weakness', 'Comfort in suffering', 'The new covenant', 'Generosity', 'Reconciliation'],
    keyPeople: ['Paul', 'Titus', 'Timothy'],
    keyEvents: [
      'The God of all comfort (ch. 1)',
      'The ministry of the new covenant (ch. 3)',
      'Treasure in jars of clay (ch. 4)',
      'The ministry of reconciliation (ch. 5)',
      'The cheerful giver (ch. 9)',
      'The thorn in the flesh (ch. 12)',
    ],
    structure: [
      { range: '1–7', title: 'The comfort and character of ministry' },
      { range: '8–9', title: 'The grace of giving' },
      { range: '10–13', title: 'The defense of apostleship' },
    ],
  },
  {
    id: 'galatians',
    name: 'Galatians',
    testament: 'NT',
    bollsBook: 48,
    chapters: 6,
    author: 'The apostle Paul',
    date: 'c. AD 48–55',
    audience: 'The churches of Galatia',
    purpose: 'To defend justification by faith alone against those demanding circumcision and law-keeping.',
    overview:
      'Galatians is Paul\'s fiery defense of the gospel: we are saved by faith in Christ, not by keeping the law. False teachers had told the Galatian believers they must be circumcised; Paul answers with his own story, the example of Abraham, and the liberating truth that in Christ there is neither Jew nor Greek. It ends with the fruit of the Spirit.',
    themes: ['Justification by faith alone', 'Freedom in Christ', 'The law vs. grace', 'The Spirit', 'The fruit of the Spirit'],
    keyPeople: ['Paul', 'Peter', 'Barnabas', 'Abraham', 'Titus'],
    keyEvents: [
      'Paul\'s rebuke: "a different gospel" (ch. 1)',
      'Confronting Peter (ch. 2)',
      'Abraham justified by faith (ch. 3)',
      'The allegory of Hagar and Sarah (ch. 4)',
      'Freedom in Christ (ch. 5)',
      'The fruit of the Spirit (ch. 5)',
    ],
    structure: [
      { range: '1–2', title: 'Paul\'s gospel defended' },
      { range: '3–4', title: 'Justification by faith explained' },
      { range: '5–6', title: 'Freedom lived by the Spirit' },
    ],
  },
  {
    id: 'ephesians',
    name: 'Ephesians',
    testament: 'NT',
    bollsBook: 49,
    chapters: 6,
    author: 'The apostle Paul (from prison in Rome)',
    date: 'c. AD 60–62',
    audience: 'The church in Ephesus and surrounding churches',
    purpose: 'To unveil God\'s cosmic plan in Christ and the church, and to call believers to worthy living.',
    overview:
      'Ephesians soars from the heights of God\'s eternal plan — chosen, redeemed, sealed, seated with Christ — to the practical walk of the Christian life: unity, purity, Spirit-filled relationships, and the armor of God. "By grace you have been saved through faith" anchors its glorious first half.',
    themes: ['Grace', 'The church as Christ\'s body', 'Unity', 'Spiritual blessings', 'The armor of God'],
    keyPeople: ['Paul', 'Tychicus'],
    keyEvents: [
      'Spiritual blessings in Christ (ch. 1)',
      'Saved by grace through faith (ch. 2)',
      'The mystery of the church (ch. 3)',
      'One body, one Spirit (ch. 4)',
      'Walking in love and light (ch. 5)',
      'The armor of God (ch. 6)',
    ],
    structure: [
      { range: '1–3', title: 'The believer\'s position in Christ' },
      { range: '4–6', title: 'The believer\'s practice in the world' },
    ],
  },
  {
    id: 'philippians',
    name: 'Philippians',
    testament: 'NT',
    bollsBook: 50,
    chapters: 4,
    author: 'The apostle Paul (from prison)',
    date: 'c. AD 60–62',
    audience: 'The church in Philippi',
    purpose: 'To thank the Philippians and to teach joy and humility through the example of Christ.',
    overview:
      'Written from prison, Philippians is the letter of joy — "rejoice" echoes through every chapter. Paul thanks the generous Philippians, urges unity through Christ\'s humble mindset (the great Christ-hymn of ch. 2), and shares his secret of contentment in every circumstance. Suffering, he shows, cannot steal Christian joy.',
    themes: ['Joy', 'Humility', 'The mind of Christ', 'Contentment', 'Partnership in the gospel'],
    keyPeople: ['Paul', 'Timothy', 'Epaphroditus', 'Euodia', 'Syntyche'],
    keyEvents: [
      'Paul\'s thanksgiving and prayer (ch. 1)',
      'The Christ-hymn: humility exalted (ch. 2)',
      'Pressing toward the goal (ch. 3)',
      '"Rejoice in the Lord always" (ch. 4)',
      'The secret of contentment (ch. 4)',
    ],
    structure: [
      { range: '1', title: 'Joy in suffering' },
      { range: '2', title: 'Joy in serving: the mind of Christ' },
      { range: '3', title: 'Joy in believing' },
      { range: '4', title: 'Joy in giving' },
    ],
  },
  {
    id: 'colossians',
    name: 'Colossians',
    testament: 'NT',
    bollsBook: 51,
    chapters: 4,
    author: 'The apostle Paul (from prison)',
    date: 'c. AD 60–62',
    audience: 'The church in Colossae',
    purpose: 'To exalt the supremacy of Christ against false teaching that diminished Him.',
    overview:
      'False teachers in Colossae were mixing Christ with angel worship, legalism, and philosophy. Paul answers with one of the New Testament\'s highest portraits of Christ — the image of the invisible God, in whom all things hold together. Believers are complete in Him and need nothing added.',
    themes: ['The supremacy of Christ', 'Completeness in Christ', 'Warning against false teaching', 'New life'],
    keyPeople: ['Paul', 'Epaphras', 'Tychicus', 'Onesimus', 'Philemon'],
    keyEvents: [
      'The supremacy of Christ (ch. 1)',
      'Complete in Christ (ch. 2)',
      'Put on the new self (ch. 3)',
      'Household instructions (ch. 3–4)',
    ],
    structure: [
      { range: '1–2', title: 'Christ supreme' },
      { range: '3–4', title: 'Christ lived out' },
    ],
  },
  {
    id: '1-thessalonians',
    name: '1 Thessalonians',
    testament: 'NT',
    bollsBook: 52,
    chapters: 5,
    author: 'The apostle Paul (with Silas and Timothy)',
    date: 'c. AD 50–51 (from Corinth)',
    audience: 'The young church in Thessalonica',
    purpose: 'To encourage a persecuted young church and to teach about the Lord\'s return.',
    overview:
      'Paul\'s earliest letter went to a church he had known only briefly before persecution drove him away. He praises their faith, defends his ministry, urges holy living, and answers their questions about believers who have died — giving the Bible\'s clearest teaching on the rapture and the comfort of Christ\'s return.',
    themes: ['The second coming', 'Holy living', 'Encouragement in persecution', 'Hope'],
    keyPeople: ['Paul', 'Silas', 'Timothy'],
    keyEvents: [
      'Thanksgiving for their faith (ch. 1)',
      'Paul\'s defense of his ministry (ch. 2)',
      'The call to holiness (ch. 4)',
      'The coming of the Lord (ch. 4)',
      'The day of the Lord (ch. 5)',
    ],
    structure: [
      { range: '1–3', title: 'Paul\'s ministry among them' },
      { range: '4–5', title: 'Holy living and the Lord\'s return' },
    ],
  },
  {
    id: '2-thessalonians',
    name: '2 Thessalonians',
    testament: 'NT',
    bollsBook: 53,
    chapters: 3,
    author: 'The apostle Paul (with Silas and Timothy)',
    date: 'c. AD 51–52',
    audience: 'The church in Thessalonica',
    purpose: 'To correct confusion about the day of the Lord and to urge steadfast, diligent living.',
    overview:
      'False teaching had alarmed the Thessalonians into thinking the day of the Lord had already come. Paul clarifies the sequence of end-time events, comforts the persecuted, and rebukes idleness — "if anyone will not work, neither shall he eat" — urging them to stand firm in the traditions they were taught.',
    themes: ['The day of the Lord', 'Perseverance', 'Diligence', 'God\'s justice'],
    keyPeople: ['Paul', 'Silas', 'Timothy'],
    keyEvents: [
      'Thanksgiving amid persecution (ch. 1)',
      'The man of lawlessness (ch. 2)',
      'Stand firm (ch. 2)',
      'Warning against idleness (ch. 3)',
    ],
    structure: [
      { range: '1', title: 'Encouragement in persecution' },
      { range: '2', title: 'Correction about the day of the Lord' },
      { range: '3', title: 'Exhortation to diligence' },
    ],
  },
  {
    id: '1-timothy',
    name: '1 Timothy',
    testament: 'NT',
    bollsBook: 54,
    chapters: 6,
    author: 'The apostle Paul',
    date: 'c. AD 62–64',
    audience: 'Timothy, Paul\'s young co-worker in Ephesus',
    purpose: 'To instruct Timothy on leading the church: sound doctrine, godly leadership, and personal godliness.',
    overview:
      'Paul writes to Timothy, left in charge at Ephesus, about how the church should be ordered. He gives qualifications for elders and deacons, warns against false teachers and the love of money, and charges Timothy to be an example in speech, conduct, love, faith, and purity. It is a manual for church leadership.',
    themes: ['Sound doctrine', 'Church leadership', 'Godliness', 'Warning against false teaching', 'Contentment'],
    keyPeople: ['Paul', 'Timothy', 'Hymenaeus', 'Alexander'],
    keyEvents: [
      'Warning against false teachers (ch. 1)',
      'Instructions on prayer and worship (ch. 2)',
      'Qualifications for elders and deacons (ch. 3)',
      'The good servant of Christ (ch. 4)',
      'The love of money (ch. 6)',
      'Fight the good fight (ch. 6)',
    ],
    structure: [
      { range: '1', title: 'Guard the gospel' },
      { range: '2–3', title: 'Order the church' },
      { range: '4–6', title: 'Shepherd faithfully' },
    ],
  },
  {
    id: '2-timothy',
    name: '2 Timothy',
    testament: 'NT',
    bollsBook: 55,
    chapters: 4,
    author: 'The apostle Paul (from prison in Rome, near death)',
    date: 'c. AD 66–67',
    audience: 'Timothy',
    purpose: 'Paul\'s final charge: guard the gospel, endure suffering, and preach the Word faithfully.',
    overview:
      'Paul\'s last letter, written from a Roman dungeon awaiting execution, is his farewell to Timothy. He urges him not to be ashamed of the gospel, to guard the treasure entrusted to him, and to preach the Word in season and out. Paul\'s own epitaph rings through: "I have fought the good fight, I have finished the race."',
    themes: ['Faithfulness', 'Endurance', 'The Word of God', 'Guarding the gospel', 'The crown of righteousness'],
    keyPeople: ['Paul', 'Timothy', 'Onesiphorus', 'Demas', 'Luke', 'Mark'],
    keyEvents: [
      'Stir up the gift of God (ch. 1)',
      'The good soldier (ch. 2)',
      'Perilous times (ch. 3)',
      'All Scripture is God-breathed (ch. 3)',
      'Preach the Word (ch. 4)',
      'Paul\'s farewell (ch. 4)',
    ],
    structure: [
      { range: '1–2', title: 'Be strong in grace' },
      { range: '3', title: 'Continue in the Scriptures' },
      { range: '4', title: 'Preach the Word; farewell' },
    ],
  },
  {
    id: 'titus',
    name: 'Titus',
    testament: 'NT',
    bollsBook: 56,
    chapters: 3,
    author: 'The apostle Paul',
    date: 'c. AD 63–65',
    audience: 'Titus, organizing the churches in Crete',
    purpose: 'To guide Titus in appointing leaders and teaching sound doctrine that produces godly living.',
    overview:
      'Paul left Titus on Crete to "set in order" the young churches. The letter gives qualifications for elders, rebukes false teachers, and shows how grace teaches us to live godly lives — with practical instructions for older and younger men and women, and servants. Good works, Paul insists, flow from the gospel.',
    themes: ['Church order', 'Sound doctrine', 'Godly living', 'Grace', 'Good works'],
    keyPeople: ['Paul', 'Titus', 'Zenas', 'Apollos'],
    keyEvents: [
      'Appoint elders (ch. 1)',
      'Rebuke false teachers (ch. 1)',
      'Teach sound doctrine (ch. 2)',
      'The grace of God that saves (ch. 2–3)',
      'Good works (ch. 3)',
    ],
    structure: [
      { range: '1', title: 'Set the church in order' },
      { range: '2', title: 'Teach sound doctrine' },
      { range: '3', title: 'Live out the gospel' },
    ],
  },
  {
    id: 'philemon',
    name: 'Philemon',
    testament: 'NT',
    bollsBook: 57,
    chapters: 1,
    author: 'The apostle Paul (from prison)',
    date: 'c. AD 60–62',
    audience: 'Philemon, a Christian slave-owner in Colossae',
    purpose: 'To appeal for Onesimus, a runaway slave, to be received back as a brother in Christ.',
    overview:
      'The shortest of Paul\'s letters is a personal appeal: Onesimus, Philemon\'s runaway slave, has become a Christian through Paul\'s ministry in prison. Paul sends him back, asking Philemon to receive him "no longer as a slave, but... a beloved brother." It is a beautiful picture of gospel reconciliation transforming human relationships.',
    themes: ['Reconciliation', 'Forgiveness', 'Brotherhood in Christ', 'Grace'],
    keyPeople: ['Paul', 'Philemon', 'Onesimus', 'Apphia', 'Archippus'],
    keyEvents: [
      'Paul\'s thanksgiving for Philemon (v. 1–7)',
      'The appeal for Onesimus (v. 8–16)',
      '"Receive him as myself" (v. 17–22)',
    ],
    structure: [{ range: '1–25', title: 'An appeal for reconciliation' }],
  },
  {
    id: 'hebrews',
    name: 'Hebrews',
    testament: 'NT',
    bollsBook: 58,
    chapters: 13,
    author: 'Unknown (traditionally associated with Paul\'s circle)',
    date: 'c. AD 60–70',
    audience: 'Jewish Christians tempted to return to Judaism',
    purpose: 'To show Christ\'s absolute superiority and to urge perseverance in faith.',
    overview:
      'Hebrews presents Jesus as better than angels, Moses, the priests, and the sacrifices — the perfect High Priest and the final sacrifice. Warning against drifting and apostasy, it calls believers to run the race with endurance, holding up the heroes of faith in chapter 11 and fixing our eyes on Jesus.',
    themes: ['The superiority of Christ', 'The new covenant', 'Faith', 'Perseverance', 'The perfect sacrifice'],
    keyPeople: ['Jesus', 'Moses', 'Melchizedek', 'Abraham'],
    keyEvents: [
      'Christ superior to angels (ch. 1–2)',
      'Christ superior to Moses (ch. 3)',
      'Jesus the great High Priest (ch. 4–5)',
      'The new covenant (ch. 8)',
      'The once-for-all sacrifice (ch. 10)',
      'The hall of faith (ch. 11)',
      'Run with endurance (ch. 12)',
    ],
    structure: [
      { range: '1–10', title: 'Christ is better' },
      { range: '11', title: 'The example of faith' },
      { range: '12–13', title: 'Run the race with endurance' },
    ],
  },
  {
    id: 'james',
    name: 'James',
    testament: 'NT',
    bollsBook: 59,
    chapters: 5,
    author: 'James, the brother of Jesus and leader of the Jerusalem church',
    date: 'c. AD 45–50',
    audience: 'Jewish Christians scattered by persecution',
    purpose: 'To show that genuine faith proves itself in works — pure religion in action.',
    overview:
      'James, likely the earliest New Testament letter, is intensely practical: trials produce perseverance, faith without works is dead, the tongue must be tamed, the rich are warned, and the sick should be prayed for. Its wisdom echoes the Sermon on the Mount and challenges every comfortable profession of faith.',
    themes: ['Faith and works', 'Trials', 'The tongue', 'Wisdom', 'Prayer', 'Care for the poor'],
    keyPeople: ['James', 'Abraham', 'Rahab', 'Elijah', 'Job'],
    keyEvents: [
      'Joy in trials (ch. 1)',
      'Faith without works is dead (ch. 2)',
      'Taming the tongue (ch. 3)',
      'Submit to God; resist the devil (ch. 4)',
      'The prayer of faith (ch. 5)',
    ],
    structure: [
      { range: '1', title: 'Faith tested by trials' },
      { range: '2', title: 'Faith proved by works' },
      { range: '3–5', title: 'Faith lived out' },
    ],
  },
  {
    id: '1-peter',
    name: '1 Peter',
    testament: 'NT',
    bollsBook: 60,
    chapters: 5,
    author: 'The apostle Peter (through Silvanus)',
    date: 'c. AD 62–64',
    audience: 'Christians scattered across Asia Minor, facing persecution',
    purpose: 'To encourage suffering believers with the living hope of Christ\'s resurrection.',
    overview:
      'Peter writes to believers as "exiles" — strangers in a hostile world — urging them to rejoice in their living hope even amid fiery trials. He teaches them to live holy lives, submit to authorities, follow Christ\'s example in suffering, and shepherd the flock. Suffering, he insists, is the normal path to glory.',
    themes: ['Living hope', 'Suffering', 'Holiness', 'Submission', 'The example of Christ'],
    keyPeople: ['Peter', 'Silvanus', 'Mark'],
    keyEvents: [
      'The living hope (ch. 1)',
      'The chosen people (ch. 2)',
      'Christ\'s example in suffering (ch. 2–3)',
      'Suffering for righteousness (ch. 4)',
      'Shepherd the flock (ch. 5)',
      'Cast your cares on Him (ch. 5)',
    ],
    structure: [
      { range: '1–2', title: 'The hope of salvation' },
      { range: '2–4', title: 'Holy living in a hostile world' },
      { range: '5', title: 'Shepherding and humility' },
    ],
  },
  {
    id: '2-peter',
    name: '2 Peter',
    testament: 'NT',
    bollsBook: 61,
    chapters: 3,
    author: 'The apostle Peter',
    date: 'c. AD 64–68 (near Peter\'s death)',
    audience: 'The same scattered believers',
    purpose: 'To warn against false teachers and to stir believers to holy living in light of Christ\'s return.',
    overview:
      'Peter\'s farewell letter warns that false teachers will secretly bring destructive heresies, denying the Lord and the promise of His coming. Against them he holds up the apostles\' eyewitness testimony, the sure word of prophecy, and the certainty of a new heavens and new earth — urging diligence, growth, and godliness.',
    themes: ['False teachers', 'The second coming', 'Growth in godliness', 'The authority of Scripture'],
    keyPeople: ['Peter', 'Paul'],
    keyEvents: [
      'Partakers of the divine nature (ch. 1)',
      'The eyewitness testimony (ch. 1)',
      'Warning against false teachers (ch. 2)',
      'The day of the Lord (ch. 3)',
      'The new heavens and new earth (ch. 3)',
    ],
    structure: [
      { range: '1', title: 'Grow in grace' },
      { range: '2', title: 'Beware false teachers' },
      { range: '3', title: 'Look for His coming' },
    ],
  },
  {
    id: '1-john',
    name: '1 John',
    testament: 'NT',
    bollsBook: 62,
    chapters: 5,
    author: 'John the apostle',
    date: 'c. AD 85–95',
    audience: 'Believers facing false teaching about Christ',
    purpose: 'To give assurance of eternal life and to expose false teachers by the tests of belief, obedience, and love.',
    overview:
      'John writes so that believers "may know that you have eternal life." Against teachers denying Christ\'s humanity, he gives three tests of genuine faith: believing Jesus is the Christ come in the flesh, obeying His commands, and loving the brothers. "God is love" anchors its warm, pastoral tone.',
    themes: ['Assurance', 'Love', 'Obedience', 'Truth vs. error', 'Fellowship with God'],
    keyPeople: ['John', 'Jesus Christ', 'The antichrists'],
    keyEvents: [
      'Walking in the light (ch. 1)',
      'The new commandment of love (ch. 2)',
      'Children of God (ch. 3)',
      'Test the spirits (ch. 4)',
      '"God is love" (ch. 4)',
      'Assurance of eternal life (ch. 5)',
    ],
    structure: [
      { range: '1–2', title: 'Fellowship with God: light and advocacy' },
      { range: '3–4', title: 'The tests: righteousness and love' },
      { range: '5', title: 'Assurance of eternal life' },
    ],
  },
  {
    id: '2-john',
    name: '2 John',
    testament: 'NT',
    bollsBook: 63,
    chapters: 1,
    author: 'John the apostle ("the elder")',
    date: 'c. AD 85–95',
    audience: '"The elect lady and her children" — a church or a Christian woman',
    purpose: 'To warn against receiving false teachers while urging believers to walk in truth and love.',
    overview:
      'John\'s brief second letter rejoices that believers are walking in truth, then warns: deceivers who deny Christ\'s coming in the flesh are abroad. Do not receive them or support their work. Truth and love must go together — love without truth is sentiment, truth without love is harshness.',
    themes: ['Truth', 'Love', 'Discernment', 'Warning against deceivers'],
    keyPeople: ['John ("the elder")', 'The elect lady'],
    keyEvents: [
      'Walking in truth and love (v. 1–6)',
      'Warning against deceivers (v. 7–11)',
      'Farewell (v. 12–13)',
    ],
    structure: [{ range: '1–13', title: 'Walk in truth; beware deceivers' }],
  },
  {
    id: '3-john',
    name: '3 John',
    testament: 'NT',
    bollsBook: 64,
    chapters: 1,
    author: 'John the apostle ("the elder")',
    date: 'c. AD 85–95',
    audience: 'Gaius, a beloved Christian leader',
    purpose: 'To commend hospitality toward traveling missionaries and to confront Diotrephes\' pride.',
    overview:
      'John\'s shortest letter praises Gaius for his hospitality to traveling preachers — "we ought to receive such." In contrast, Diotrephes, who loves to be first, refuses them and must be confronted. The letter commends Demetrius as a good example. It is a window into the life of the early church.',
    themes: ['Hospitality', 'Support for missionaries', 'Humility vs. pride', 'Walking in truth'],
    keyPeople: ['John ("the elder")', 'Gaius', 'Diotrephes', 'Demetrius'],
    keyEvents: [
      'Commendation of Gaius (v. 1–8)',
      'The rebuke of Diotrephes (v. 9–11)',
      'The good testimony of Demetrius (v. 12)',
    ],
    structure: [{ range: '1–14', title: 'Commend hospitality; confront pride' }],
  },
  {
    id: 'jude',
    name: 'Jude',
    testament: 'NT',
    bollsBook: 65,
    chapters: 1,
    author: 'Jude, the brother of James (and of Jesus)',
    date: 'c. AD 65–80',
    audience: 'Believers threatened by false teachers',
    purpose: 'To urge believers to contend earnestly for the faith against ungodly infiltrators.',
    overview:
      'Jude\'s urgent letter calls believers to "contend for the faith" against false teachers who had crept into the church, turning grace into license. Using examples from Israel\'s history, angels, and Sodom, he warns of their doom. The letter closes with one of the New Testament\'s most beloved doxologies.',
    themes: ['Contending for the faith', 'False teachers', 'Judgment', 'Perseverance', 'Doxology'],
    keyPeople: ['Jude', 'Enoch', 'Michael', 'Cain', 'Balaam', 'Korah'],
    keyEvents: [
      'The call to contend (v. 3)',
      'Examples of judgment (v. 5–7)',
      'Woes on the false teachers (v. 11–13)',
      'Enoch\'s prophecy (v. 14–15)',
      'The doxology (v. 24–25)',
    ],
    structure: [{ range: '1–25', title: 'Contend for the faith' }],
  },
  {
    id: 'revelation',
    name: 'Revelation',
    testament: 'NT',
    bollsBook: 66,
    chapters: 22,
    author: 'John the apostle',
    date: 'c. AD 95 (during Domitian\'s persecution)',
    audience: 'The seven churches of Asia — and all persecuted believers',
    purpose: 'To reveal the risen Christ\'s triumph and to encourage suffering believers with the certainty of His victory.',
    overview:
      'Revelation is John\'s apocalyptic vision of the risen Christ, given on Patmos. Letters to seven churches give way to cosmic scenes of judgment and worship, the war between the Lamb and the beast, and the final triumph: a new heaven and new earth where God dwells with His people. It ends with the church\'s prayer: "Come, Lord Jesus."',
    themes: ['The triumph of the Lamb', 'Judgment', 'Worship', 'Perseverance', 'The new creation'],
    keyPeople: ['Jesus Christ', 'John', 'The seven churches', 'The beast', 'The Lamb'],
    keyEvents: [
      'The vision of the risen Christ (ch. 1)',
      'Letters to the seven churches (ch. 2–3)',
      'The throne of God (ch. 4–5)',
      'The seals, trumpets, and bowls (ch. 6–16)',
      'The fall of Babylon (ch. 17–18)',
      'The marriage supper of the Lamb (ch. 19)',
      'The new heaven and new earth (ch. 21–22)',
    ],
    structure: [
      { range: '1–3', title: 'The risen Christ and His churches' },
      { range: '4–16', title: 'The judgments of God' },
      { range: '17–20', title: 'The fall of evil' },
      { range: '21–22', title: 'The new creation' },
    ],
  }
);

export function getBook(id: string): Book | undefined {
  return BOOKS.find((b) => b.id === id);
}
