export interface Person {
  id: string;
  name: string;
  who: string;
  context: string;
  family: string[];
  events: string[];
  keyPassages: string[];
  lessons: string[];
  failures: string[];
  faithExamples: string[];
  related: string[];
}

export const PEOPLE: Person[] = [
  {
    id: 'adam',
    name: 'Adam',
    who: 'The first man, created by God from the dust and given life by God\'s breath; the federal head of the human race whose disobedience brought sin and death into the world.',
    context:
      'Adam lived in the perfect world of Genesis 1–2, placed in the Garden of Eden to work and keep it, given Eve as his wife, and commanded not to eat from the tree of the knowledge of good and evil. His story explains the origin of human sin, suffering, and death — and sets up the need for the "last Adam," Jesus Christ.',
    family: ['Eve (wife)', 'Cain, Abel, Seth (sons)', 'Numerous other sons and daughters (Gen. 5:4)'],
    events: [
      'Created from dust; God breathes life into him (Gen. 2:7)',
      'Placed in Eden to work and keep the garden (Gen. 2:15)',
      'Names the animals; receives Eve as wife (Gen. 2:19–25)',
      'Eats the forbidden fruit with Eve (Gen. 3:6)',
      'Hides from God; blames Eve (Gen. 3:8–12)',
      'Cursed with toil; expelled from Eden (Gen. 3:17–24)',
      'Fathers Seth, through whom the godly line continues (Gen. 4:25–5:3)',
    ],
    keyPassages: ['Genesis 1:26–28', 'Genesis 2', 'Genesis 3', 'Genesis 5:1–5', 'Romans 5:12–21', '1 Corinthians 15:22, 45'],
    lessons: [
      'One act of disobedience can have cosmic consequences — sin is never private.',
      'Blame-shifting is sin\'s native language; confession is grace\'s.',
      'God seeks sinners even when they hide ("Where are you?").',
      'Humanity\'s ruin in Adam points to its rescue in Christ, the last Adam.',
    ],
    failures: [
      'Ate the forbidden fruit, disobeying God\'s direct command',
      'Stood by passively while Eve was deceived, then joined her',
      'Blamed Eve — and implicitly God — instead of repenting',
    ],
    faithExamples: [
      'Named his wife Eve ("life") in faith, believing God\'s promise of offspring despite the curse (Gen. 3:20)',
    ],
    related: ['eve', 'noah', 'abraham'],
  },
  {
    id: 'eve',
    name: 'Eve',
    who: 'The first woman, formed from Adam\'s rib to be his helper and wife; "the mother of all living." She was the first to be deceived by the serpent and to eat the forbidden fruit.',
    context:
      'Eve shared Adam\'s perfect beginning and tragic fall. Yet God gave her a unique honor: through her offspring would come the One who crushes the serpent (Gen. 3:15). Her story holds both the sorrow of sin\'s entrance and the first promise of redemption.',
    family: ['Adam (husband)', 'Cain, Abel, Seth (sons)'],
    events: [
      'Created from Adam\'s rib as his helper (Gen. 2:21–23)',
      'Deceived by the serpent; eats the forbidden fruit (Gen. 3:1–6)',
      'Gives the fruit to Adam (Gen. 3:6)',
      'Hears God\'s judgment: pain in childbirth, yet the promise of offspring (Gen. 3:16)',
      'Receives the protoevangelium: her seed will crush the serpent (Gen. 3:15)',
      'Bears Cain, Abel, and Seth (Gen. 4:1–2, 25)',
    ],
    keyPassages: ['Genesis 2:18–25', 'Genesis 3', 'Genesis 4:1–2, 25', '1 Timothy 2:13–14', '2 Corinthians 11:3'],
    lessons: [
      'Temptation follows a pattern: doubt God\'s word, deny His warning, desire what He withheld.',
      'God\'s judgment on sin never cancels His promise of redemption.',
      'The first gospel promise came to the first sinner — grace pursues the guilty.',
      'Marriage was God\'s good design before sin distorted it.',
    ],
    failures: [
      'Engaged the serpent instead of fleeing; doubted God\'s word',
      'Ate the forbidden fruit and led her husband into sin',
    ],
    faithExamples: [
      'Acknowledged God\'s gift in Cain\'s birth: "I have gotten a man with the help of the LORD" (Gen. 4:1)',
      'Named Seth in hope, believing God had "appointed" another offspring (Gen. 4:25)',
    ],
    related: ['adam', 'abraham', 'mary'],
  },
  {
    id: 'noah',
    name: 'Noah',
    who: 'A righteous man in a corrupt generation whom God chose to preserve humanity and the animals through the flood; the second father of the human race and recipient of God\'s covenant with all living things.',
    context:
      'Noah lived around 2500 BC (traditional dating) in a world so violent and corrupt that God grieved making humanity. "Noah found favor in the eyes of the LORD" and "walked with God." He preached righteousness for 120 years while building the ark, then repopulated the earth after the flood.',
    family: ['Shem, Ham, Japheth (sons)', 'His wife (unnamed)', 'Lamech (father)', 'Methuselah (grandfather)'],
    events: [
      'Finds favor with God in a corrupt generation (Gen. 6:8)',
      'Builds the ark over decades, preaching righteousness (Gen. 6:14–22; 2 Pet. 2:5)',
      'Enters the ark with his family and the animals (Gen. 7)',
      'Survives the flood; sends out the dove (Gen. 7–8)',
      'Offers sacrifice; God establishes the Noahic covenant and the rainbow (Gen. 8:20–9:17)',
      'Plants a vineyard; becomes drunk; Ham dishonors him (Gen. 9:20–27)',
    ],
    keyPassages: ['Genesis 6–9', 'Hebrews 11:7', '1 Peter 3:20', '2 Peter 2:5', 'Matthew 24:37–39'],
    lessons: [
      'Obedience often looks foolish to the world — build the ark anyway.',
      'God judges sin but always preserves a remnant by grace.',
      'One person\'s righteousness can shelter a whole family.',
      'God keeps His covenant promises — the rainbow is His signature.',
    ],
    failures: [
      'Became drunk after the flood, leading to shame and family strife (Gen. 9:21)',
    ],
    faithExamples: [
      'Built the ark "in reverent fear," condemning the world and becoming an heir of righteousness (Heb. 11:7)',
      'Did "all that God commanded him" (Gen. 6:22) — complete obedience over decades',
    ],
    related: ['adam', 'abraham', 'moses'],
  },
  {
    id: 'abraham',
    name: 'Abraham',
    who: 'The father of the faithful and of the Israelite nation; called by God from idolatry in Ur to receive the covenant promises of land, descendants, and blessing to all nations.',
    context:
      'Abram (later Abraham, "father of many") lived c. 2000 BC. God called him to leave Mesopotamia for Canaan, promising to make him a great nation. His life — marked by extraordinary faith and real failures — became the Bible\'s supreme example of justification by faith (Gen. 15:6; Rom. 4).',
    family: ['Sarah (wife)', 'Hagar (concubine)', 'Isaac (son of promise)', 'Ishmael (son by Hagar)', 'Terah (father)', 'Lot (nephew)'],
    events: [
      'Called from Ur to Canaan (Gen. 12:1–9)',
      'Believes God\'s promise; counted righteous (Gen. 15:6)',
      'Receives the covenant of circumcision; name changed (Gen. 17)',
      'Pleads for Sodom (Gen. 18)',
      'Offers Isaac on Mount Moriah (Gen. 22)',
      'Buys the cave of Machpelah; buries Sarah (Gen. 23)',
      'Dies at 175, "full of years" (Gen. 25:7–8)',
    ],
    keyPassages: ['Genesis 12', 'Genesis 15', 'Genesis 17', 'Genesis 22', 'Romans 4', 'Galatians 3', 'Hebrews 11:8–19'],
    lessons: [
      'Faith is trusting God\'s promise enough to act on it — "he went out, not knowing where."',
      'Righteousness comes by believing, not achieving (Gen. 15:6).',
      'God\'s plan advances by His faithfulness, not our perfection.',
      'Intercession matters: Abraham pleaded for Sodom and for others.',
    ],
    failures: [
      'Lied about Sarah being his sister — twice (Gen. 12, 20)',
      'Fathered Ishmael through Hagar, trying to fulfill God\'s promise by human scheming (Gen. 16)',
      'Laughed in unbelief at the promise of a son (Gen. 17:17)',
    ],
    faithExamples: [
      'Left Ur for an unknown land in simple obedience (Gen. 12:4; Heb. 11:8)',
      'Believed God\'s impossible promise of descendants like the stars (Gen. 15:5–6)',
      'Offered Isaac, reasoning God could raise him from the dead (Gen. 22; Heb. 11:17–19)',
    ],
    related: ['sarah', 'isaac', 'jacob', 'moses'],
  },
  {
    id: 'sarah',
    name: 'Sarah',
    who: 'Abraham\'s wife and the mother of Isaac, the child of promise; honored in the New Testament as a model of faith and holy womanhood despite her long barrenness.',
    context:
      'Sarai (later Sarah, "princess") shared Abraham\'s 25-year wait for the promised son, enduring barrenness in a culture where childlessness meant shame. Her story moves from scheming (Hagar) to laughter (disbelief) to miraculous motherhood at 90 — a testament to God\'s power to give life to the dead.',
    family: ['Abraham (husband)', 'Isaac (son)', 'Terah (father-in-law)'],
    events: [
      'Leaves Ur with Abraham for Canaan (Gen. 12:5)',
      'Taken into Pharaoh\'s and Abimelech\'s households; God protects her (Gen. 12, 20)',
      'Gives Hagar to Abraham; Ishmael is born (Gen. 16)',
      'Name changed; promised a son at 90 (Gen. 17:15–16)',
      'Laughs at the promise; bears Isaac (Gen. 18:12; 21:1–7)',
      'Has Hagar and Ishmael sent away (Gen. 21:8–14)',
      'Dies at 127; buried in Machpelah (Gen. 23)',
    ],
    keyPassages: ['Genesis 16–18', 'Genesis 21', 'Genesis 23', 'Hebrews 11:11', '1 Peter 3:5–6', 'Galatians 4:21–31'],
    lessons: [
      'God\'s delays are not denials — He keeps promises on His timetable.',
      'Trying to fulfill God\'s promise by human scheming (Hagar) brings sorrow.',
      'It\'s never too late for God: barrenness at 90 became motherhood.',
      'Faith can grow: Sarah moved from laughter of doubt to the joy of fulfillment.',
    ],
    failures: [
      'Gave Hagar to Abraham, creating lasting family conflict (Gen. 16)',
      'Laughed in unbelief at God\'s promise, then denied it (Gen. 18:12–15)',
      'Treated Hagar harshly (Gen. 16:6)',
    ],
    faithExamples: [
      'Received strength to conceive past childbearing age, "since she considered him faithful who had promised" (Heb. 11:11)',
      'Called "holy women" model who hoped in God and respected Abraham (1 Pet. 3:5–6)',
    ],
    related: ['abraham', 'isaac', 'mary'],
  },
  {
    id: 'isaac',
    name: 'Isaac',
    who: 'The miracle son of Abraham and Sarah, born when they were 100 and 90; the child of promise through whom God\'s covenant continued; a type of Christ in his near-sacrifice on Moriah.',
    context:
      'Isaac ("laughter") embodied God\'s faithfulness to impossible promises. His life was quieter than his father\'s or son\'s — marked by meditation, wells, and peacemaking — yet he carried the covenant line and foreshadowed Christ as the beloved son offered up.',
    family: ['Abraham (father)', 'Sarah (mother)', 'Rebekah (wife)', 'Esau and Jacob (twin sons)', 'Ishmael (half-brother)'],
    events: [
      'Miraculously born to aged parents (Gen. 21:1–7)',
      'Nearly sacrificed on Mount Moriah; God provides a ram (Gen. 22)',
      'Marries Rebekah (Gen. 24)',
      'Prays for Rebekah\'s barrenness; twins are born (Gen. 25:21–26)',
      'Deceived by Jacob into giving the blessing (Gen. 27)',
      'Re-digs his father\'s wells; makes peace with Abimelech (Gen. 26)',
      'Dies at 180 (Gen. 35:28–29)',
    ],
    keyPassages: ['Genesis 21–22', 'Genesis 24–27', 'Hebrews 11:20', 'Galatians 4:28', 'Romans 9:7'],
    lessons: [
      'God keeps impossible promises — in His time, not ours.',
      'A quiet, faithful life can carry God\'s purposes as surely as a dramatic one.',
      'Peacemaking (re-digging wells, yielding) reflects God\'s heart.',
      'Favoritism wounds families for generations.',
    ],
    failures: [
      'Favored Esau over Jacob, contributing to family division (Gen. 25:28)',
      'Repeated his father\'s lie about his wife being his sister (Gen. 26:7)',
      'Tried to bless Esau against God\'s revealed purpose (Gen. 27)',
    ],
    faithExamples: [
      'Trusted his father on Mount Moriah, carrying the wood without resistance (Gen. 22:6)',
      'Blessed Jacob and Esau "by faith... concerning the future" (Heb. 11:20)',
      'Meditated in the fields; prayed persistently for his wife (Gen. 24:63; 25:21)',
    ],
    related: ['abraham', 'sarah', 'jacob'],
  },
  {
    id: 'jacob',
    name: 'Jacob',
    who: 'The scheming younger twin who became Israel, father of the twelve tribes; his life traces God\'s transforming grace from deceiver to prince with God.',
    context:
      'Jacob ("heel-grabber," "deceiver") lived c. 1900 BC. Chosen before birth over Esau, he spent decades grasping blessing by trickery — deceiving his father, outwitting Laban — until God wrestled him at Peniel, renamed him Israel ("strives with God"), and made him the father of the nation.',
    family: ['Isaac (father)', 'Rebekah (mother)', 'Esau (twin brother)', 'Leah and Rachel (wives)', 'Twelve sons (the tribes)', 'Dinah (daughter)'],
    events: [
      'Buys Esau\'s birthright for stew (Gen. 25:29–34)',
      'Deceives Isaac to steal the blessing; flees (Gen. 27)',
      'Dreams of the ladder at Bethel (Gen. 28)',
      'Works 20 years for Laban; marries Leah and Rachel (Gen. 29–31)',
      'Wrestles with God at Peniel; renamed Israel (Gen. 32)',
      'Reconciled with Esau (Gen. 33)',
      'Loses Joseph; reunited in Egypt (Gen. 37, 45–46)',
      'Blesses his sons and Pharaoh; dies in Egypt (Gen. 47–49)',
    ],
    keyPassages: ['Genesis 25–35', 'Genesis 37–50', 'Hosea 12:3–4', 'Hebrews 11:21'],
    lessons: [
      'God\'s election doesn\'t excuse our scheming — but His grace transforms schemers.',
      'You can\'t wrestle God and walk away unchanged; surrender brings blessing.',
      'Favoritism (Joseph\'s coat) repeats the sins of previous generations.',
      'God\'s promises survive our failures — He is the God of Jacob.',
    ],
    failures: [
      'Deceived his blind father to steal Esau\'s blessing (Gen. 27)',
      'Manipulated and schemed for advantage much of his life',
      'Showed blatant favoritism to Joseph, provoking his brothers\' hatred',
    ],
    faithExamples: [
      'Clung to God at Peniel: "I will not let you go unless you bless me" (Gen. 32:26)',
      'Built altars and worshiped at Bethel and Shechem (Gen. 28, 33, 35)',
      'Blessed Joseph\'s sons by faith, worshiping on his staff (Heb. 11:21)',
    ],
    related: ['isaac', 'joseph', 'abraham'],
  },
  {
    id: 'joseph',
    name: 'Joseph',
    who: 'Jacob\'s favored son, sold into slavery by his brothers, who rose by God\'s providence to rule Egypt and save his family from famine; the Old Testament\'s clearest picture of providence and a type of Christ.',
    context:
      'Joseph lived c. 1700 BC. His story (Gen. 37–50, the longest in Genesis) moves from pit to palace: betrayed by brothers, falsely accused by Potiphar\'s wife, forgotten in prison — yet God was with him at every step, raising him to save Egypt and his own family, bringing Israel down to Egypt.',
    family: ['Jacob (father)', 'Rachel (mother)', 'Benjamin (full brother)', 'Eleven brothers', 'Asenath (wife)', 'Manasseh and Ephraim (sons)'],
    events: [
      'Receives the ornate robe; shares prophetic dreams (Gen. 37)',
      'Sold by his brothers; taken to Egypt (Gen. 37:28)',
      'Serves Potiphar; resists his wife\'s advances; imprisoned (Gen. 39)',
      'Interprets dreams in prison; forgotten by the cupbearer (Gen. 40)',
      'Interprets Pharaoh\'s dreams; made vizier of Egypt (Gen. 41)',
      'Tests and forgives his brothers (Gen. 42–45)',
      'Settles his family in Goshen; dies at 110 (Gen. 46–50)',
    ],
    keyPassages: ['Genesis 37', 'Genesis 39–45', 'Genesis 50:20', 'Psalm 105:17–22', 'Acts 7:9–14', 'Hebrews 11:22'],
    lessons: [
      '"You meant evil against me, but God meant it for good" — providence overrules malice.',
      'Integrity in obscurity (prison) prepares for influence in prominence (palace).',
      'Forgiveness frees both the forgiven and the forgiver.',
      'God\'s delays (13 years from pit to palace) serve His larger story.',
    ],
    failures: [
      'As a youth, tattled on his brothers and flaunted his dreams, provoking hatred (Gen. 37:2–11)',
    ],
    faithExamples: [
      'Refused Potiphar\'s wife: "How then can I do this great wickedness and sin against God?" (Gen. 39:9)',
      'Credited God for dream interpretations (Gen. 40:8; 41:16)',
      'Forgave his brothers and saw God\'s hand in their evil (Gen. 45:5–8; 50:20)',
      'By faith gave instructions about his bones and the Exodus (Heb. 11:22)',
    ],
    related: ['jacob', 'moses', 'daniel'],
  },
  {
    id: 'moses',
    name: 'Moses',
    who: 'The great prophet, lawgiver, and deliverer of Israel; raised in Pharaoh\'s palace, called at the burning bush, who led the Exodus, received the Law at Sinai, and spoke with God "face to face."',
    context:
      'Moses (c. 1526–1406 BC) bridged Israel\'s slavery and nationhood. After 40 years as an Egyptian prince and 40 as a Midianite shepherd, he spent his final 40 years leading some two million Israelites through the wilderness — performing signs, receiving the Law, and interceding for a rebellious people.',
    family: ['Amram and Jochebed (parents)', 'Aaron (brother)', 'Miriam (sister)', 'Zipporah (wife)', 'Gershom and Eliezer (sons)'],
    events: [
      'Saved from Pharaoh\'s decree; raised in the palace (Ex. 2:1–10)',
      'Flees to Midian after killing an Egyptian (Ex. 2:11–15)',
      'Called at the burning bush (Ex. 3–4)',
      'Confronts Pharaoh; ten plagues; the Exodus (Ex. 5–14)',
      'Parts the Red Sea (Ex. 14)',
      'Receives the Ten Commandments at Sinai (Ex. 20, 31)',
      'Intercedes after the golden calf (Ex. 32)',
      'Strikes the rock twice; barred from Canaan (Num. 20)',
      'Dies on Mount Nebo; buried by God (Deut. 34)',
    ],
    keyPassages: ['Exodus 3–4', 'Exodus 14', 'Exodus 20', 'Exodus 32–34', 'Numbers 12', 'Deuteronomy 34', 'Hebrews 11:23–29'],
    lessons: [
      'God\'s presence ("I will be with you") qualifies the called, not their ability.',
      'Meekness is strength under control — Moses was the meekest man on earth (Num. 12:3).',
      'Intercession can turn away wrath; leaders stand in the gap.',
      'One moment of disobedience can have lasting consequences, even for giants.',
    ],
    failures: [
      'Killed an Egyptian in anger and tried to hide it (Ex. 2:12)',
      'Struck the rock instead of speaking to it, dishonoring God before Israel (Num. 20:11–12)',
    ],
    faithExamples: [
      'Chose suffering with God\'s people over Egypt\'s treasures (Heb. 11:24–26)',
      'Interceded for Israel after the golden calf, offering his own life (Ex. 32:32)',
      'Kept the Passover and led Israel through the sea by faith (Heb. 11:28–29)',
    ],
    related: ['joshua', 'abraham', 'elijah'],
  },
  {
    id: 'joshua',
    name: 'Joshua',
    who: 'Moses\' successor who led Israel into the Promised Land, conquering Canaan through courageous obedience; his name (Yeshua) is the Hebrew form of "Jesus."',
    context:
      'Joshua served as Moses\' aide for 40 years — at the Red Sea, at Sinai, in the tabernacle — before leading Israel c. 1406 BC. His book records the conquest and division of Canaan, closing with his famous charge: "Choose this day whom you will serve... as for me and my house, we will serve the LORD."',
    family: ['Nun (father)'],
    events: [
      'Leads Israel against Amalek while Moses prays (Ex. 17:8–13)',
      'One of two faithful spies; survives the wilderness (Num. 13–14)',
      'Commissioned as Moses\' successor (Num. 27:18–23; Deut. 31)',
      'Leads Israel across the Jordan (Josh. 3–4)',
      'Conquers Jericho and Canaan (Josh. 6–12)',
      'Divides the land among the tribes (Josh. 13–21)',
      'Renews the covenant at Shechem; dies at 110 (Josh. 24)',
    ],
    keyPassages: ['Numbers 13–14', 'Joshua 1', 'Joshua 3–6', 'Joshua 24', 'Hebrews 11:30'],
    lessons: [
      'Courage flows from God\'s promise, not our strength: "Be strong and courageous."',
      'Meditating on God\'s word day and night is the path to success (Josh. 1:8).',
      'Obedience in strange methods (marching around Jericho) brings victory.',
      'Leaders must call people to decisive commitment.',
    ],
    failures: [
      'Made a treaty with the deceptive Gibeonites without consulting God (Josh. 9:14)',
    ],
    faithExamples: [
      '"We are well able to overcome it" — faithful spy amid unbelief (Num. 13:30)',
      'Led the conquest trusting God\'s promises (Heb. 11:30)',
      '"As for me and my house, we will serve the LORD" (Josh. 24:15)',
    ],
    related: ['moses', 'david'],
  },
];
PEOPLE.push(
  {
    id: 'david',
    name: 'David',
    who: 'Israel\'s greatest king, the shepherd boy who became the warrior-poet; "a man after God\'s own heart" and recipient of the covenant promising an everlasting dynasty fulfilled in Christ.',
    context:
      'David (c. 1040–970 BC) rose from Bethlehem\'s pastures to Jerusalem\'s throne. His reign united Israel, captured Jerusalem, and brought the ark home. His grievous sin with Bathsheba and sincere repentance (Ps. 51) make him both a warning and an encouragement; his psalms have taught God\'s people to pray for 3,000 years.',
    family: ['Jesse (father)', 'Michal, Abigail, Bathsheba (wives)', 'Amnon, Absalom, Adonijah, Solomon (sons)', 'Tamar (daughter)'],
    events: [
      'Anointed by Samuel while tending sheep (1 Sam. 16)',
      'Defeats Goliath with sling and stone (1 Sam. 17)',
      'Serves Saul; flees his jealousy for years (1 Sam. 18–26)',
      'Twice spares Saul\'s life (1 Sam. 24, 26)',
      'Becomes king; captures Jerusalem (2 Sam. 5)',
      'Receives the Davidic covenant (2 Sam. 7)',
      'Sins with Bathsheba; confronted by Nathan; repents (2 Sam. 11–12)',
      'Endures Absalom\'s rebellion (2 Sam. 15–18)',
      'Dies, charging Solomon to walk with God (1 Kings 2)',
    ],
    keyPassages: ['1 Samuel 16–17', '2 Samuel 7', '2 Samuel 11–12', 'Psalms 23, 51', 'Acts 13:22', 'Revelation 22:16'],
    lessons: [
      'God looks at the heart, not outward appearance (1 Sam. 16:7).',
      'Courage comes from remembering God\'s past faithfulness (the lion, the bear, Goliath).',
      'No one is beyond repentance — or beyond consequences.',
      'Worship in every season: David sang in caves and palaces.',
    ],
    failures: [
      'Committed adultery with Bathsheba and arranged Uriah\'s murder (2 Sam. 11)',
      'Took a census in pride, bringing plague on Israel (2 Sam. 24)',
      'Failed to discipline Amnon and Absalom, fueling family tragedy',
    ],
    faithExamples: [
      'Faced Goliath trusting God, not armor: "The battle is the LORD\'s" (1 Sam. 17:47)',
      'Refused to kill Saul, honoring God\'s anointed (1 Sam. 24, 26)',
      'Repented deeply when confronted: "I have sinned against the LORD" (2 Sam. 12:13; Ps. 51)',
      'Gave generously for the temple he would never build (1 Chron. 29)',
    ],
    related: ['joshua', 'solomon'],
  },
  {
    id: 'solomon',
    name: 'Solomon',
    who: 'David\'s son and Israel\'s third king, famed for God-given wisdom, builder of the first temple, and author of Proverbs, Ecclesiastes, and the Song of Solomon.',
    context:
      'Solomon (c. 970–930 BC) inherited a united kingdom at its height. His prayer for wisdom pleased God, who added wealth and honor. He built the magnificent temple and a trading empire — but his many foreign wives turned his heart to idolatry, and his kingdom split after his death.',
    family: ['David (father)', 'Bathsheba (mother)', 'Rehoboam (son and successor)', '700 wives and 300 concubines'],
    events: [
      'Asks God for wisdom; receives wisdom, wealth, and honor (1 Kings 3)',
      'Judges wisely between the two mothers (1 Kings 3:16–28)',
      'Builds and dedicates the temple (1 Kings 6–8)',
      'Hosts the Queen of Sheba (1 Kings 10)',
      'Marries foreign wives; builds high places for their gods (1 Kings 11)',
      'Warned by God; kingdom prophesied to split (1 Kings 11:9–13)',
      'Dies after 40-year reign (1 Kings 11:42–43)',
    ],
    keyPassages: ['1 Kings 3–11', 'Proverbs 1–9', 'Ecclesiastes 12', 'Matthew 12:42'],
    lessons: [
      'Ask God for wisdom — He gives generously (James 1:5).',
      'A good beginning doesn\'t guarantee a good ending; guard your heart.',
      'Disobedience in "small" compromises (foreign wives) leads to idolatry.',
      'Apart from God, even the greatest achievements are "vanity."',
    ],
    failures: [
      'Married hundreds of foreign wives who turned his heart to other gods (1 Kings 11:1–8)',
      'Accumulated horses, wives, and wealth against God\'s command for kings (Deut. 17:16–17)',
      'Heavy taxation and forced labor bred resentment that split the kingdom',
    ],
    faithExamples: [
      'Prayed for wisdom to govern God\'s people rather than riches (1 Kings 3:9)',
      'Dedicated the temple with a magnificent prayer (1 Kings 8)',
      'Wrote Proverbs\' call to "trust in the LORD with all your heart" (Prov. 3:5)',
    ],
    related: ['david', 'elijah'],
  },
  {
    id: 'elijah',
    name: 'Elijah',
    who: 'The fiery prophet of Israel who confronted King Ahab and the prophets of Baal on Mount Carmel; taken to heaven in a whirlwind without dying.',
    context:
      'Elijah ministered c. 870–850 BC during Israel\'s darkest idolatry under Ahab and Jezebel. His sudden appearances, miracles, and Mount Carmel triumph made him Israel\'s most dramatic prophet. Jews expected his return before the Messiah (Mal. 4:5) — fulfilled in John the Baptist\'s ministry (Luke 1:17).',
    family: ['None recorded; from Tishbe in Gilead'],
    events: [
      'Prophesies drought; fed by ravens at the Kerith Ravine (1 Kings 17:1–7)',
      'Sustained by the widow of Zarephath; raises her son (1 Kings 17:8–24)',
      'Defeats 850 prophets of Baal on Mount Carmel (1 Kings 18)',
      'Flees Jezebel; fed by an angel; hears God\'s "still small voice" (1 Kings 19)',
      'Anoints Elisha as successor (1 Kings 19:19–21)',
      'Confronts Ahab over Naboth\'s vineyard (1 Kings 21)',
      'Taken to heaven in a whirlwind (2 Kings 2:11)',
      'Appears with Moses at the Transfiguration (Matt. 17:3)',
    ],
    keyPassages: ['1 Kings 17–19', '1 Kings 21', '2 Kings 2', 'Malachi 4:5–6', 'James 5:17–18', 'Matthew 17:1–8'],
    lessons: [
      'One person with God is a majority — stand alone if you must.',
      'God is not only in the fire and earthquake but in the gentle whisper.',
      'Even great prophets battle depression; God restores with rest, food, and purpose.',
      'Prayer moves heaven: Elijah\'s prayers stopped and started the rain.',
    ],
    failures: [
      'Fled in fear from Jezebel after Carmel\'s triumph, despairing of life (1 Kings 19:3–4)',
    ],
    faithExamples: [
      'Prayed earnestly and the rain stopped for 3½ years, then returned (James 5:17–18)',
      'Faced 850 false prophets alone on Carmel, trusting God to send fire (1 Kings 18)',
      'Obeyed God\'s word to anoint his successor and confront kings',
    ],
    related: ['moses', 'daniel', 'john-the-baptist'],
  },
  {
    id: 'isaiah',
    name: 'Isaiah',
    who: 'The great evangelical prophet of Judah who ministered to kings and foretold the Messiah — His virgin birth, suffering, and glory — with unmatched clarity.',
    context:
      'Isaiah ("the LORD saves"), son of Amoz, prophesied c. 740–680 BC in Jerusalem under Uzziah, Jotham, Ahaz, and Hezekiah. His 66-chapter book — sometimes called "the fifth Gospel" — moves from judgment to comfort, climaxing in the Suffering Servant of chapter 53.',
    family: ['Amoz (father)', 'Wife ("the prophetess")', 'Shear-jashub and Maher-shalal-hash-baz (sons)'],
    events: [
      'Called by a vision of God\'s holiness in the temple (Isa. 6)',
      'Confronts King Ahaz; gives the Immanuel sign (Isa. 7)',
      'Counsels Hezekiah during Assyria\'s invasion (Isa. 36–37)',
      'Prophesies the Suffering Servant (Isa. 53)',
      'Foretells the new heavens and new earth (Isa. 65–66)',
      'Tradition: martyred under Manasseh (Heb. 11:37, "sawn in two")',
    ],
    keyPassages: ['Isaiah 6', 'Isaiah 7:14', 'Isaiah 9:6–7', 'Isaiah 40', 'Isaiah 53', 'Romans 10:16'],
    lessons: [
      'Seeing God\'s holiness produces conviction ("Woe is me") and commission ("Here am I").',
      'Comfort flows from God\'s sovereignty: He uses even Assyria and Babylon.',
      'Prophecy proves Scripture\'s divine origin — written centuries before fulfillment.',
      'True hope looks beyond judgment to the coming King and new creation.',
    ],
    failures: [],
    faithExamples: [
      'Answered God\'s call without hesitation: "Here am I! Send me" (Isa. 6:8)',
      'Preached judgment and hope faithfully for 60 years to unresponsive kings',
      'Stood with Hezekiah in prayer when Assyria threatened Jerusalem (Isa. 37)',
    ],
    related: ['jeremiah', 'daniel', 'elijah'],
  },
  {
    id: 'jeremiah',
    name: 'Jeremiah',
    who: 'The weeping prophet who preached to Judah for 40 years before its fall, enduring rejection and persecution while promising the new covenant.',
    context:
      'Jeremiah began prophesying c. 627 BC as a young man and continued through Jerusalem\'s destruction in 586 BC. Called "the weeping prophet," he watched his warnings come true — and gave God\'s people the Bible\'s clearest promise of the new covenant (Jer. 31:31–34).',
    family: ['Hilkiah (father, a priest)', 'Forbidden to marry as a sign (Jer. 16:2)'],
    events: [
      'Called as a youth; objects, "I am only a youth" (Jer. 1:4–10)',
      'Preaches the temple sermon; threatened with death (Jer. 7, 26)',
      'Dictates prophecies to Baruch; the scroll is burned (Jer. 36)',
      'Thrown into a cistern; rescued by Ebed-melech (Jer. 38)',
      'Witnesses Jerusalem\'s fall; laments (Jer. 39; Lam.)',
      'Forcibly taken to Egypt by rebels; prophesies there (Jer. 43–44)',
    ],
    keyPassages: ['Jeremiah 1', 'Jeremiah 7', 'Jeremiah 18', 'Jeremiah 29:11', 'Jeremiah 31:31–34', 'Lamentations 3'],
    lessons: [
      'Faithfulness is measured by obedience, not results — Jeremiah preached 40 years with little response.',
      'God\'s call overrides our inadequacy: "Do not say, I am only a youth."',
      'Even in judgment, God plans hope: "plans to give you a future" was written to exiles.',
      'Tears for sinners reflect God\'s own heart.',
    ],
    failures: [],
    faithExamples: [
      'Preached unpopular truth for decades despite beatings, stocks, and a cistern (Jer. 20, 37–38)',
      'Bought a field during the siege as a sign of future restoration (Jer. 32)',
      'Stayed with the remnant in Judah after the fall, sharing their fate (Jer. 40)',
    ],
    related: ['isaiah', 'daniel'],
  },
  {
    id: 'daniel',
    name: 'Daniel',
    who: 'The Jewish exile who rose to the highest offices of Babylon and Persia through integrity and God-given wisdom; prophet of God\'s sovereign kingdom and recipient of apocalyptic visions.',
    context:
      'Daniel was taken to Babylon as a youth c. 605 BC and served four kings over 70 years. His book pairs court stories (the fiery furnace, the lions\' den) with visions of coming kingdoms and the Son of Man — foundational for New Testament eschatology.',
    family: ['Of royal/Judahite descent (Dan. 1:3)', 'No family recorded in exile'],
    events: [
      'Resolves not to defile himself with the king\'s food (Dan. 1:8)',
      'Interprets Nebuchadnezzar\'s dream (Dan. 2)',
      'Interprets the handwriting on the wall (Dan. 5)',
      'Survives the lions\' den under Darius (Dan. 6)',
      'Receives visions of four beasts and the Son of Man (Dan. 7)',
      'Prays the great confession of chapter 9; learns of the seventy weeks',
      'Sees the glorious man; receives final visions (Dan. 10–12)',
    ],
    keyPassages: ['Daniel 1', 'Daniel 2', 'Daniel 6', 'Daniel 7:13–14', 'Daniel 9', 'Ezekiel 14:14', 'Matthew 24:15'],
    lessons: [
      'Resolve your convictions early — Daniel decided before the pressure came.',
      'Excellence and integrity open doors that scheming cannot.',
      'Prayer is non-negotiable: three times daily, windows open, whatever the law says.',
      'God rules the kingdoms of men — empires rise and fall at His word.',
    ],
    failures: [],
    faithExamples: [
      'Chose vegetables over defilement as a teenager in a pagan court (Dan. 1:8–16)',
      'Prayed openly despite the lions\'-den decree (Dan. 6:10)',
      'Confessed his people\'s sins as his own in Daniel 9',
      '"An excellent spirit was in him" — trusted by pagan kings for 70 years (Dan. 6:3)',
    ],
    related: ['joseph', 'esther', 'elijah'],
  },
  {
    id: 'esther',
    name: 'Esther',
    who: 'The Jewish orphan who became queen of Persia and risked her life to save her people from genocide; heroine of the book of Esther and namesake of the feast of Purim.',
    context:
      'Esther (Hadassah) lived c. 480 BC in Susa, raised by her cousin Mordecai. Chosen as queen to Xerxes (Ahasuerus), she concealed her Jewish identity until Haman\'s plot forced her to act — approaching the king unsummoned at the risk of death.',
    family: ['Mordecai (cousin and guardian)', 'Parents died in her youth'],
    events: [
      'Taken into the king\'s harem; chosen queen (Est. 2)',
      'Haman plots to exterminate the Jews (Est. 3)',
      'Mordecai\'s challenge: "for such a time as this" (Est. 4:14)',
      'Risks her life approaching the king; invites him to banquets (Est. 5)',
      'Exposes Haman; he is hanged on his own gallows (Est. 7)',
      'Jews defended; Purim instituted (Est. 8–9)',
    ],
    keyPassages: ['Esther 2', 'Esther 4:14–16', 'Esther 7', 'Esther 9'],
    lessons: [
      'God positions people "for such a time as this" — your place is providential.',
      'Courage means acting despite fear, not without it ("if I perish, I perish").',
      'God\'s name never appears in Esther — yet His providence is on every page.',
      'Fasting and prayer precede bold action.',
    ],
    failures: [],
    faithExamples: [
      'Approached the king unsummoned to plead for her people (Est. 5:1–2)',
      'Called for three days of fasting before acting (Est. 4:16)',
      'Used wisdom and timing — two banquets — rather than rushing (Est. 5, 7)',
    ],
    related: ['daniel', 'mary', 'joseph'],
  },
  {
    id: 'mary',
    name: 'Mary (mother of Jesus)',
    who: 'The virgin chosen by God to bear Jesus; her humble faith and "let it be" surrender made her the most honored woman in history.',
    context:
      'Mary was a young Galilean virgin engaged to Joseph when Gabriel announced she would bear the Messiah by the Holy Spirit (c. 6–4 BC). She treasured and pondered God\'s works, stood by the cross, and prayed with the disciples at Pentecost.',
    family: ['Joseph (husband)', 'Jesus (son)', 'James, Joseph, Simon, Judas (other sons)', 'Elizabeth (relative)'],
    events: [
      'The Annunciation: Gabriel\'s visit (Luke 1:26–38)',
      'Visits Elizabeth; sings the Magnificat (Luke 1:39–56)',
      'Bears Jesus in Bethlehem (Luke 2:1–20)',
      'Flees to Egypt; returns to Nazareth (Matt. 2)',
      'Finds 12-year-old Jesus in the temple (Luke 2:41–52)',
      'At the wedding in Cana: "Do whatever he tells you" (John 2:1–11)',
      'Stands at the cross; entrusted to John (John 19:25–27)',
      'Prays with the disciples before Pentecost (Acts 1:14)',
    ],
    keyPassages: ['Luke 1:26–56', 'Luke 2', 'John 2:1–11', 'John 19:25–27', 'Acts 1:14'],
    lessons: [
      'God uses the humble and obscure — a village girl became the Messiah\'s mother.',
      'True faith says "let it be to me according to your word," whatever the cost.',
      'Ponder God\'s works: Mary "treasured up all these things" (Luke 2:19).',
      'Faithfulness means staying — even at the cross.',
    ],
    failures: [],
    faithExamples: [
      '"Behold, I am the servant of the Lord; let it be to me according to your word" (Luke 1:38)',
      'Sang the Magnificat, rejoicing in God her Savior (Luke 1:46–55)',
      'Believed when she couldn\'t understand, treasuring mysteries (Luke 2:19, 51)',
    ],
    related: ['joseph-husband-of-mary', 'sarah'],
  },
);
PEOPLE.push(
  {
    id: 'joseph-husband-of-mary',
    name: 'Joseph (husband of Mary)',
    who: 'The righteous carpenter of Nazareth chosen to be Jesus\' earthly father; his quiet obedience protected Mary and the infant Messiah.',
    context:
      'Joseph was a tekton (craftsman) descended from David, engaged to Mary when he learned of her pregnancy. Rather than shaming her, he planned a quiet divorce — until an angel revealed the child was conceived by the Holy Spirit. His obedience at each step fulfilled prophecy and sheltered the Savior\'s childhood.',
    family: ['Mary (wife)', 'Jesus (adopted son)', 'James, Joseph, Simon, Judas (sons)', 'David (ancestor)'],
    events: [
      'Plans to divorce Mary quietly; angel appears in a dream (Matt. 1:18–25)',
      'Takes Mary as wife; names the child Jesus (Matt. 1:24–25)',
      'Travels to Bethlehem for the census (Luke 2:1–7)',
      'Flees to Egypt to escape Herod (Matt. 2:13–15)',
      'Returns and settles in Nazareth (Matt. 2:19–23)',
      'Searches three days for 12-year-old Jesus in Jerusalem (Luke 2:41–50)',
    ],
    keyPassages: ['Matthew 1:18–25', 'Matthew 2', 'Luke 2:1–52'],
    lessons: [
      'Righteousness and mercy belong together — Joseph was just and kind.',
      'God guides the obedient step by step, often through dreams and Scripture.',
      'Quiet faithfulness matters enormously in God\'s plan.',
      'Adoptive love is real love: Joseph raised God\'s Son as his own.',
    ],
    failures: [],
    faithExamples: [
      'Obeyed the angel immediately, taking Mary as wife despite the scandal (Matt. 1:24)',
      'Rose at night to flee to Egypt, protecting the Christ child (Matt. 2:14)',
      'Returned and settled in Nazareth in obedience to divine warnings (Matt. 2:22–23)',
    ],
    related: ['mary', 'david'],
  },
  {
    id: 'john-the-baptist',
    name: 'John the Baptist',
    who: 'The forerunner of Christ who prepared His way, preaching repentance and baptizing in the Jordan; the greatest of the prophets, who decreased so Christ might increase.',
    context:
      'John was miraculously born to aged Zechariah and Elizabeth (c. 6 BC). Living austerely in the wilderness, he called Israel to repentance, baptized Jesus, and pointed disciples to "the Lamb of God." He was beheaded by Herod Antipas for confronting the king\'s adultery.',
    family: ['Zechariah (father, priest)', 'Elizabeth (mother)', 'Jesus (relative)'],
    events: [
      'Miraculous birth announced to Zechariah (Luke 1:5–25, 57–80)',
      'Preaches repentance in the wilderness (Matt. 3:1–12)',
      'Baptizes Jesus; sees the Spirit descend (Matt. 3:13–17)',
      '"Behold, the Lamb of God!" — points disciples to Jesus (John 1:29–37)',
      'Imprisoned for rebuking Herod\'s adultery (Mark 6:17–20)',
      'Sends disciples to ask, "Are you the one?" — Jesus reassures him (Matt. 11:2–6)',
      'Beheaded at Herod\'s birthday feast (Mark 6:21–29)',
    ],
    keyPassages: ['Luke 1', 'Matthew 3', 'John 1:19–37', 'John 3:22–30', 'Mark 6:14–29', 'Matthew 11:7–15'],
    lessons: [
      'Greatness is making much of Christ and little of self: "He must increase, I must decrease."',
      'Prepare the way: point people to Jesus, not to yourself.',
      'Faithfulness may cost your life — speak truth to power anyway.',
      'Even strong believers have dark nights; bring your doubts to Jesus.',
    ],
    failures: [],
    faithExamples: [
      'Lived with radical simplicity and preached repentance without fear (Matt. 3:4–7)',
      'Refused to inflate his role: "I am not the Christ" (John 1:20; 3:28)',
      'Rejoiced to see his own disciples leave him for Jesus (John 3:29)',
    ],
    related: ['elijah', 'mary', 'peter'],
  },
  {
    id: 'peter',
    name: 'Peter',
    who: 'The impulsive fisherman who became the apostles\' leader; preacher at Pentecost, "rock" of the early church, and author of two epistles.',
    context:
      'Simon (renamed Peter, "rock") was a Galilean fisherman called with his brother Andrew. He walked on water, confessed Christ, denied Him three times, was restored by the risen Jesus, and led the church at Pentecost. Tradition holds he was crucified upside-down in Rome under Nero (c. AD 64).',
    family: ['Andrew (brother)', 'Wife (mentioned in 1 Cor. 9:5; mother-in-law healed in Mark 1:30)', 'Jonah/John (father)'],
    events: [
      'Called from fishing nets to follow Jesus (Matt. 4:18–20)',
      'Walks on water — then sinks (Matt. 14:28–31)',
      'Confesses: "You are the Christ, the Son of the living God" (Matt. 16:16)',
      'Rebuked by Jesus: "Get behind me, Satan" (Matt. 16:23)',
      'Denies Jesus three times (Matt. 26:69–75)',
      'Restored by the risen Christ: "Feed my sheep" (John 21:15–19)',
      'Preaches at Pentecost; 3,000 saved (Acts 2)',
      'Opens the gospel to Gentiles at Cornelius\'s house (Acts 10)',
      'Writes 1–2 Peter; martyred in Rome (tradition)',
    ],
    keyPassages: ['Matthew 16:13–23', 'Luke 22:54–62', 'John 21', 'Acts 2', 'Acts 10', '1 Peter 5', '2 Peter 1'],
    lessons: [
      'Failure isn\'t final: Christ restores deniers and recommissions them.',
      'Boldness comes from the Spirit, not temperament — compare Peter before and after Pentecost.',
      'Leaders must be willing to be corrected (by Jesus, by Paul in Gal. 2).',
      'Suffering is normal for believers; entrust yourself to the faithful Creator.',
    ],
    failures: [
      'Denied knowing Jesus three times on the night of His trial (Matt. 26:69–75)',
      'Rebuked Jesus about the cross and was called "Satan" (Matt. 16:22–23)',
      'Withdrew from Gentile believers under pressure; rebuked by Paul (Gal. 2:11–14)',
      'Sank when he took his eyes off Jesus (Matt. 14:30)',
    ],
    faithExamples: [
      '"Lord, to whom shall we go? You have the words of eternal life" (John 6:68)',
      'Preached Christ boldly before the Sanhedrin (Acts 4:8–12)',
      'Healed the lame, raised Dorcas, and opened the door to Gentiles (Acts 3, 9, 10)',
      'Wrote of hope amid suffering, shepherding the flock humbly (1 Pet. 5:1–4)',
    ],
    related: ['john-the-baptist', 'paul', 'john-apostle'],
  },
  {
    id: 'paul',
    name: 'Paul',
    who: 'The apostle to the Gentiles; former persecutor of the church transformed on the Damascus road into Christianity\'s greatest missionary and theologian, author of thirteen New Testament letters.',
    context:
      'Saul of Tarsus was a zealous Pharisee who hunted Christians until the risen Jesus confronted him (c. AD 33). Renamed Paul, he planted churches across the Roman Empire on three missionary journeys, endured beatings, shipwrecks, and imprisonments, and was likely martyred in Rome under Nero (c. AD 64–67).',
    family: ['Of Benjamin; Roman citizen; trained under Gamaliel', 'Sister and nephew (Acts 23:16)'],
    events: [
      'Persecutes the church; present at Stephen\'s stoning (Acts 7:58; 8:1–3)',
      'Converted on the Damascus road (Acts 9:1–19)',
      'Preaches in Damascus and Arabia; confirmed by the apostles (Gal. 1:15–24)',
      'First missionary journey with Barnabas (Acts 13–14)',
      'Jerusalem council: gospel freed from circumcision (Acts 15)',
      'Second and third journeys; Ephesian ministry (Acts 16–20)',
      'Arrested in Jerusalem; appeals to Caesar (Acts 21–26)',
      'Shipwrecked; preaches in Rome under house arrest (Acts 27–28)',
      'Writes the epistles; executed in Rome (tradition; 2 Tim. 4)',
    ],
    keyPassages: ['Acts 9', 'Acts 13–28', 'Romans', 'Galatians', 'Philippians 3', '2 Timothy 4', '1 Corinthians 15:9–10'],
    lessons: [
      'No one is beyond grace — the chief persecutor became the chief apostle.',
      'Suffering is the normal cost of mission; God\'s strength is perfected in weakness.',
      'Theology must become doxology and practice — Paul\'s letters always apply the gospel.',
      'Finish well: "I have fought the good fight... kept the faith."',
    ],
    failures: [
      'Persecuted and imprisoned Christians; consented to Stephen\'s death (Acts 8:1; 22:20)',
      'Sharp disagreement with Barnabas over John Mark split their partnership (Acts 15:36–40)',
    ],
    faithExamples: [
      'Counted all his achievements as loss for Christ (Phil. 3:7–8)',
      'Endured beatings, stonings, and shipwrecks without quitting (2 Cor. 11:23–28)',
      'Sang hymns in a Philippian jail at midnight (Acts 16:25)',
      'Faced execution with hope: "to die is gain" (Phil. 1:21; 2 Tim. 4:6–8)',
    ],
    related: ['peter', 'john-apostle', 'james-brother-of-jesus'],
  },
  {
    id: 'james-brother-of-jesus',
    name: 'James (brother of Jesus)',
    who: 'Jesus\' skeptical younger brother who became a believer after the resurrection, leader of the Jerusalem church, and author of the epistle of James.',
    context:
      'James grew up with Jesus but didn\'t believe during His ministry (John 7:5). The risen Christ appeared to him personally (1 Cor. 15:7), transforming him into "James the Just," the respected leader of the Jerusalem church who moderated the Jerusalem council (Acts 15) and wrote the intensely practical letter of James.',
    family: ['Mary (mother)', 'Joseph (father)', 'Jesus (eldest brother)', 'Joseph, Simon, Judas (brothers)'],
    events: [
      'Disbelieves during Jesus\' ministry (John 7:3–5)',
      'Sees the risen Christ (1 Cor. 15:7)',
      'Becomes leader of the Jerusalem church (Acts 12:17; 15:13; 21:18)',
      'Moderates the Jerusalem council, freeing Gentiles from circumcision (Acts 15:13–21)',
      'Receives Paul\'s collection and counsels him (Acts 21:17–25)',
      'Writes the epistle of James (c. AD 45–50)',
      'Martyred in Jerusalem c. AD 62 (Josephus)',
    ],
    keyPassages: ['John 7:5', '1 Corinthians 15:7', 'Acts 15', 'Acts 21:17–25', 'James 1–5', 'Galatians 1:19; 2:9'],
    lessons: [
      'Proximity to Jesus isn\'t faith — James grew up with Him yet needed the resurrection.',
      'God uses skeptics: the doubting brother became the church\'s pillar.',
      'True faith proves itself in works — James\'s lifelong theme.',
      'Wise leaders build bridges: James united Jewish and Gentile believers.',
    ],
    failures: [
      'Mocked Jesus\' ministry with unbelieving brothers (John 7:3–5)',
    ],
    faithExamples: [
      'Led the Jerusalem church with wisdom and prayer (tradition: "camel knees" from praying)',
      'Championed Gentile freedom at the Jerusalem council (Acts 15:19)',
      'Wrote the New Testament\'s most practical letter on living faith (James)',
      'Remained in dangerous Jerusalem, shepherding the mother church until martyrdom',
    ],
    related: ['paul', 'peter', 'mary'],
  },
  {
    id: 'john-apostle',
    name: 'John (apostle)',
    who: 'The beloved disciple, son of thunder turned apostle of love; author of John\'s Gospel, three epistles, and Revelation.',
    context:
      'John, son of Zebedee, was a Galilean fisherman called with his brother James. Part of Jesus\' inner circle (with Peter and James), he reclined next to Jesus at the Last Supper, stood at the cross, outran Peter to the tomb, and later led the Ephesian church. Exiled to Patmos under Domitian, he received Revelation (c. AD 95).',
    family: ['Zebedee (father)', 'Salome (mother)', 'James (brother, "son of thunder")'],
    events: [
      'Called from fishing with James (Matt. 4:21–22)',
      'Witnesses the Transfiguration (Matt. 17:1–8)',
      'At the Last Supper, "the disciple whom Jesus loved" (John 13:23)',
      'Stands at the cross; receives Mary (John 19:26–27)',
      'First to the empty tomb; believes (John 20:1–8)',
      'Restored and commissioned by the Sea of Galilee (John 21)',
      'Leads the Jerusalem church with Peter (Acts 3–4, 8)',
      'Exiled to Patmos; writes Revelation (Rev. 1:9)',
      'Writes Gospel and epistles from Ephesus (tradition)',
    ],
    keyPassages: ['John 13:23', 'John 19:26–27', 'John 20–21', '1 John 4', 'Revelation 1', 'Mark 3:17'],
    lessons: [
      'Intimacy with Jesus transforms character — "son of thunder" became the apostle of love.',
      'Love is Christianity\'s mark: "By this all will know you are my disciples" (John 13:35).',
      'Stay when others flee: John stood at the cross.',
      'Truth and love are inseparable — John fought heresy fiercely and loved deeply.',
    ],
    failures: [
      'With James, wanted to call fire on Samaritans; rebuked by Jesus (Luke 9:54–55)',
      'Sought seats of glory beside Jesus in His kingdom (Mark 10:35–40)',
      'Fled with the others at Jesus\' arrest (Mark 14:50)',
    ],
    faithExamples: [
      'Reclined on Jesus\' breast — the posture of intimacy (John 13:23)',
      'Stood at the cross when others fled (John 19:26)',
      'Believed at the empty tomb seeing the graveclothes (John 20:8)',
      'Received and recorded the Revelation of Jesus Christ (Rev. 1:1)',
    ],
    related: ['peter', 'paul', 'mary'],
  },
);

export function getPerson(id: string): Person | undefined {
  return PEOPLE.find((p) => p.id === id);
}
