import type { QuizQuestion } from '@/lib/types';

export const QUIZ_BANK: QuizQuestion[] = [
  // ---- PAUL ----
  { id: 'quiz-paul-1', type: 'mc', prompt: 'In which city was Saul (Paul) born?', choices: ['Jerusalem', 'Tarsus', 'Antioch', 'Rome'], answer: 'Tarsus', explanation: 'Acts 22:3 — Paul was born in Tarsus of Cilicia.', tags: ['paul', 'people-nt'] },
  { id: 'quiz-paul-2', type: 'mc', prompt: 'What was Paul\'s trade?', choices: ['Fisherman', 'Tentmaker', 'Tax collector', 'Carpenter'], answer: 'Tentmaker', explanation: 'Acts 18:3 — Paul worked with his hands as a tentmaker.', tags: ['paul'] },
  { id: 'quiz-paul-3', type: 'tf', prompt: 'It is certain that Paul wrote the book of Hebrews.', answer: 'False', explanation: 'Hebrews\' authorship is unknown; Paul\'s authorship is debated, not certain.', tags: ['paul', 'nt-overview'] },
  { id: 'quiz-paul-4', type: 'fill', prompt: 'Complete Philippians 1:21: "For me to live is ___, to die is gain."', answer: 'Christ', explanation: 'Paul\'s summary of life\'s purpose in one sentence.', tags: ['paul'] },
  { id: 'quiz-paul-5', type: 'matching', prompt: 'Match each letter (A–D) to its description (1–4): A. Romans  B. Philemon  C. Galatians  D. Philippians — 1. Shortest letter, about Onesimus  2. Joy written from prison  3. "Foolish Galatians" — grace vs. law  4. The gospel explained systematically', choices: ['A-4, B-1, C-3, D-2', 'A-1, B-2, C-3, D-4', 'A-3, B-4, C-1, D-2', 'A-2, B-3, C-4, D-1'], answer: 'A-4, B-1, C-3, D-2', explanation: 'Romans is the systematic gospel; Philemon concerns Onesimus; Galatians defends grace; Philippians overflows with joy.', tags: ['paul'] },
  // ---- GENESIS ----
  { id: 'quiz-genesis-1', type: 'mc', prompt: 'Who was sold into slavery by his brothers?', choices: ['Judah', 'Joseph', 'Benjamin', 'Reuben'], answer: 'Joseph', explanation: 'Genesis 37 — Joseph\'s brothers sold him to Ishmaelites.', tags: ['genesis', 'people-ot'] },
  { id: 'quiz-genesis-2', type: 'tf', prompt: 'The Tower of Babel account is found in Genesis 11.', answer: 'True', explanation: 'Genesis 11:1-9 — God confused languages at Babel.', tags: ['genesis'] },
  { id: 'quiz-genesis-3', type: 'fill', prompt: 'God tested Abraham by asking him to sacrifice his son ___ on Mount Moriah.', answer: 'Isaac', explanation: 'Genesis 22 — pointing to God\'s own sacrifice of his Son.', tags: ['genesis'] },
  { id: 'quiz-genesis-4', type: 'mc', prompt: 'On which day did God rest from creation?', choices: ['The first day', 'The sixth day', 'The seventh day', 'He never rested'], answer: 'The seventh day', explanation: 'Genesis 2:2 — God rested on the seventh day, blessing it.', tags: ['genesis'] },
  { id: 'quiz-genesis-5', type: 'matching', prompt: 'Match each person (A–D) to the correct fact (1–4): A. Adam  B. Noah  C. Abraham  D. Jacob — 1. Built the ark  2. Renamed Israel  3. The first man  4. Father of many nations', choices: ['A-3, B-1, C-4, D-2', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-2, D-1', 'A-2, B-4, C-1, D-3'], answer: 'A-3, B-1, C-4, D-2', explanation: 'Adam was first; Noah built the ark; Abraham fathered nations; Jacob became Israel.', tags: ['genesis', 'people-ot'] },
  // ---- EXODUS ----
  { id: 'quiz-exodus-1', type: 'mc', prompt: 'Who led Israel out of Egypt?', choices: ['Aaron', 'Joshua', 'Moses', 'Caleb'], answer: 'Moses', explanation: 'Exodus 3-14 — God called Moses to deliver Israel.', tags: ['exodus', 'people-ot'] },
  { id: 'quiz-exodus-2', type: 'fill', prompt: 'God parted the ___ Sea so Israel could escape Pharaoh\'s army.', answer: 'Red', explanation: 'Exodus 14 — the Red Sea crossing.', tags: ['exodus'] },
  { id: 'quiz-exodus-3', type: 'tf', prompt: 'The Ten Commandments were given at Mount Sinai.', answer: 'True', explanation: 'Exodus 20 — after redemption from Egypt, God gave the covenant law.', tags: ['exodus'] },
  { id: 'quiz-exodus-4', type: 'mc', prompt: 'How many plagues did God send on Egypt?', choices: ['7', '10', '12', '3'], answer: '10', explanation: 'Exodus 7-12 — ten plagues culminating in the Passover.', tags: ['exodus'] },
  { id: 'quiz-exodus-5', type: 'matching', prompt: 'Match each term (A–D) to its meaning (1–4): A. Passover  B. Manna  C. Golden calf  D. Tabernacle — 1. Bread from heaven  2. Israel\'s idolatry at Sinai  3. Lamb\'s blood on the doorposts  4. God\'s dwelling among Israel', choices: ['A-3, B-1, C-2, D-4', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-1, D-2', 'A-2, B-4, C-1, D-3'], answer: 'A-3, B-1, C-2, D-4', explanation: 'Passover: blood on doorposts; manna: heaven\'s bread; golden calf: Sinai idolatry; tabernacle: God dwelling with his people.', tags: ['exodus'] },
  // ---- JESUS-BIRTH ----
  { id: 'quiz-jesus-birth-1', type: 'mc', prompt: 'In which town was Jesus born?', choices: ['Nazareth', 'Bethlehem', 'Capernaum', 'Jerusalem'], answer: 'Bethlehem', explanation: 'Matthew 2:1; Luke 2:4-7 — fulfilling Micah 5:2.', tags: ['jesus-birth'] },
  { id: 'quiz-jesus-birth-2', type: 'mc', prompt: 'Who was king of Judea when Jesus was born?', choices: ['Herod the Great', 'Pontius Pilate', 'Caesar Augustus', 'Herod Antipas'], answer: 'Herod the Great', explanation: 'Matthew 2:1 — Herod tried to kill the newborn king.', tags: ['jesus-birth', 'timeline'] },
  { id: 'quiz-jesus-birth-3', type: 'tf', prompt: 'Jesus was born in a palace in Jerusalem.', answer: 'False', explanation: 'He was born in Bethlehem and laid in a manger (Luke 2:7).', tags: ['jesus-birth'] },
  { id: 'quiz-jesus-birth-4', type: 'fill', prompt: 'The angel told Joseph to name Mary\'s child ___.', answer: 'Jesus', explanation: 'Matthew 1:21 — "for he will save his people from their sins."', tags: ['jesus-birth'] },
  { id: 'quiz-jesus-birth-5', type: 'matching', prompt: 'Match each figure (A–D) to the correct fact (1–4): A. Mary  B. Joseph  C. Magi  D. Shepherds — 1. Visited by angels in the fields  2. Brought gold, frankincense, and myrrh  3. Jesus\' earthly father figure  4. Jesus\' mother', choices: ['A-4, B-3, C-2, D-1', 'A-1, B-2, C-3, D-4', 'A-3, B-4, C-1, D-2', 'A-2, B-1, C-4, D-3'], answer: 'A-4, B-3, C-2, D-1', explanation: 'Mary: mother; Joseph: guardian; Magi: gift-bearers; shepherds: first witnesses.', tags: ['jesus-birth'] },
  // ---- JESUS-MINISTRY ----
  { id: 'quiz-jesus-ministry-1', type: 'mc', prompt: 'About how long was Jesus\' public ministry?', choices: ['One year', 'About three years', 'Ten years', 'Forty years'], answer: 'About three years', explanation: 'From his baptism (~AD 27) to the cross (~AD 30).', tags: ['jesus-ministry', 'timeline'] },
  { id: 'quiz-jesus-ministry-2', type: 'tf', prompt: 'Jesus was baptized by John the Baptist.', answer: 'True', explanation: 'Matthew 3:13-17 — the Father\'s voice and the Spirit\'s descent.', tags: ['jesus-ministry'] },
  { id: 'quiz-jesus-ministry-3', type: 'fill', prompt: 'At Cana, Jesus\' first miracle turned water into ___.', answer: 'wine', explanation: 'John 2:1-11 — the first of his signs.', tags: ['jesus-ministry', 'miracles'] },
  { id: 'quiz-jesus-ministry-4', type: 'mc', prompt: 'Jesus most often taught the crowds using...', choices: ['Philosophical essays', 'Parables', 'Legal codes', 'Poems only'], answer: 'Parables', explanation: 'Earthly stories with heavenly meanings (Matthew 13).', tags: ['jesus-ministry', 'parables'] },
  { id: 'quiz-jesus-ministry-5', type: 'matching', prompt: 'Match each person (A–D) to the encounter (1–4): A. Nicodemus  B. Samaritan woman  C. Zacchaeus  D. Rich young ruler — 1. "You must be born again"  2. Told to sell all he had  3. Tax collector who climbed a tree  4. "Give me a drink" at the well', choices: ['A-1, B-4, C-3, D-2', 'A-4, B-1, C-2, D-3', 'A-2, B-3, C-4, D-1', 'A-3, B-2, C-1, D-4'], answer: 'A-1, B-4, C-3, D-2', explanation: 'Nicodemus: born again; Samaritan woman: the well; Zacchaeus: the tree; rich young ruler: sell all.', tags: ['jesus-ministry'] },
  // ---- MIRACLES ----
  { id: 'quiz-miracles-1', type: 'mc', prompt: 'About how many men did Jesus feed with five loaves and two fish?', choices: ['500', '5,000', '12', '70'], answer: '5,000', explanation: 'John 6:10 — plus women and children; twelve baskets left over.', tags: ['miracles'] },
  { id: 'quiz-miracles-2', type: 'tf', prompt: 'Jesus walked on water.', answer: 'True', explanation: 'Matthew 14:25 — then Peter walked briefly too.', tags: ['miracles'] },
  { id: 'quiz-miracles-3', type: 'fill', prompt: 'Jesus raised ___ from the dead after he had been buried four days.', answer: 'Lazarus', explanation: 'John 11 — "I am the resurrection and the life."', tags: ['miracles', 'death-resurrection'] },
  { id: 'quiz-miracles-4', type: 'mc', prompt: 'How did Jesus heal the man born blind in John 9?', choices: ['With a prayer cloth', 'He made mud with spit and put it on his eyes', 'With anointing oil only', 'By laying on hands silently'], answer: 'He made mud with spit and put it on his eyes', explanation: 'John 9:6 — then told him to wash in Siloam.', tags: ['miracles'] },
  { id: 'quiz-miracles-5', type: 'matching', prompt: 'Match each miracle (A–D) to its detail (1–4): A. Calming the storm  B. Water to wine  C. Ten lepers  D. Fig tree — 1. First sign, at Cana  2. "Peace! Be still!"  3. Cleansed, but only one returned  4. Withered for fruitlessness', choices: ['A-2, B-1, C-3, D-4', 'A-1, B-2, C-4, D-3', 'A-4, B-3, C-2, D-1', 'A-3, B-4, C-1, D-2'], answer: 'A-2, B-1, C-3, D-4', explanation: 'Storm: "Peace! Be still"; Cana: first sign; lepers: one thankful; fig tree: judged fruitless.', tags: ['miracles'] },

  // ---- PARABLES ----
  { id: 'quiz-parables-1', type: 'mc', prompt: 'In the parable of the Good Samaritan, the wounded man was traveling from Jerusalem to...', choices: ['Bethlehem', 'Jericho', 'Nazareth', 'Capernaum'], answer: 'Jericho', explanation: 'Luke 10:30 — the dangerous "Way of Blood."', tags: ['parables'] },
  { id: 'quiz-parables-2', type: 'tf', prompt: 'In the parable of the prodigal son, the older brother joyfully celebrated his brother\'s return.', answer: 'False', explanation: 'Luke 15:28 — he was angry and refused to go in.', tags: ['parables'] },
  { id: 'quiz-parables-3', type: 'fill', prompt: 'In the parable of the sower, the seed represents God\'s ___.', answer: 'word', explanation: 'Luke 8:11 — "The seed is the word of God."', tags: ['parables'] },
  { id: 'quiz-parables-4', type: 'mc', prompt: 'The parable of the talents primarily teaches...', choices: ['Invest in stocks', 'Faithfulness with what God entrusts to us', 'Bury your gifts safely', 'Equality of outcomes'], answer: 'Faithfulness with what God entrusts to us', explanation: 'Matthew 25:14-30 — "Well done, good and faithful servant."', tags: ['parables'] },
  { id: 'quiz-parables-5', type: 'matching', prompt: 'Match each parable (A–D) to its theme (1–4): A. Mustard seed  B. Lost sheep  C. Great banquet  D. Unforgiving servant — 1. The kingdom\'s small beginnings  2. Forgiven much, yet refused to forgive  3. Excuses for missing the feast  4. One of a hundred is sought', choices: ['A-1, B-4, C-3, D-2', 'A-4, B-1, C-2, D-3', 'A-2, B-3, C-4, D-1', 'A-3, B-2, C-1, D-4'], answer: 'A-1, B-4, C-3, D-2', explanation: 'Mustard seed: small beginnings; lost sheep: the one sought; banquet: excuses; unforgiving servant: forgiven yet unforgiving.', tags: ['parables'] },
  // ---- TEACHINGS ----
  { id: 'quiz-teachings-1', type: 'mc', prompt: '"You are the salt of the earth" comes from...', choices: ['The Sermon on the Mount', 'The Olivet Discourse', 'The Upper Room', 'The parables'], answer: 'The Sermon on the Mount', explanation: 'Matthew 5:13 — disciples preserve and flavor the world.', tags: ['teachings'] },
  { id: 'quiz-teachings-2', type: 'tf', prompt: 'Jesus commanded his followers to love their enemies.', answer: 'True', explanation: 'Matthew 5:44 — "Love your enemies... pray for those who persecute you."', tags: ['teachings'] },
  { id: 'quiz-teachings-3', type: 'fill', prompt: 'Complete Matthew 7:7: "Ask, and it will be ___ to you."', answer: 'given', explanation: 'Ask, seek, knock — the Father gives good gifts.', tags: ['teachings', 'prayer'] },
  { id: 'quiz-teachings-4', type: 'mc', prompt: 'The Golden Rule teaches us to...', choices: ['Treat others as they treat you', 'Treat others as you want to be treated', 'Avoid other people', 'Treat others as your inferiors'], answer: 'Treat others as you want to be treated', explanation: 'Matthew 7:12 — "Whatever you desire for men to do to you, you shall also do to them."', tags: ['teachings'] },
  { id: 'quiz-teachings-5', type: 'matching', prompt: 'Match each teaching (A–D) to its content (1–4): A. Beatitudes  B. Lord\'s Prayer  C. Golden Rule  D. Narrow gate — 1. "Do to others as you would have them do to you"  2. "Blessed are the poor in spirit"  3. Two ways: life or destruction  4. "Our Father in heaven"', choices: ['A-2, B-4, C-1, D-3', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-2, D-1', 'A-3, B-1, C-4, D-2'], answer: 'A-2, B-4, C-1, D-3', explanation: 'Beatitudes open the Sermon; the Lord\'s Prayer models praying; the Golden Rule summarizes ethics; the narrow gate demands decision.', tags: ['teachings'] },
  // ---- DISCIPLES ----
  { id: 'quiz-disciples-1', type: 'mc', prompt: 'Which disciple betrayed Jesus?', choices: ['Peter', 'Judas Iscariot', 'Thomas', 'Matthew'], answer: 'Judas Iscariot', explanation: 'Matthew 26:14-16 — for thirty pieces of silver.', tags: ['disciples', 'people-nt'] },
  { id: 'quiz-disciples-2', type: 'tf', prompt: 'Peter denied knowing Jesus three times.', answer: 'True', explanation: 'Luke 22:54-62 — before the rooster crowed.', tags: ['disciples'] },
  { id: 'quiz-disciples-3', type: 'fill', prompt: 'The "beloved disciple" is traditionally identified as the apostle ___.', answer: 'John', explanation: 'John 21:24 — author of the Gospel, letters, and Revelation.', tags: ['disciples', 'people-nt'] },
  { id: 'quiz-disciples-4', type: 'mc', prompt: 'Which disciple had been a tax collector?', choices: ['Peter', 'Andrew', 'Matthew', 'Bartholomew'], answer: 'Matthew', explanation: 'Matthew 9:9 — also called Levi.', tags: ['disciples', 'people-nt'] },
  { id: 'quiz-disciples-5', type: 'matching', prompt: 'Match each disciple (A–D) to the fact (1–4): A. Peter  B. Thomas  C. Andrew  D. John — 1. Brought Peter to Jesus  2. "My Lord and my God!"  3. Denied Christ three times  4. A "son of thunder"', choices: ['A-3, B-2, C-1, D-4', 'A-1, B-4, C-3, D-2', 'A-2, B-3, C-4, D-1', 'A-4, B-1, C-2, D-3'], answer: 'A-3, B-2, C-1, D-4', explanation: 'Peter: denial; Thomas: confession; Andrew: brought Peter; John: son of thunder.', tags: ['disciples'] },
  // ---- DEATH-RESURRECTION ----
  { id: 'quiz-death-resurrection-1', type: 'mc', prompt: 'Jesus was crucified at a place called...', choices: ['Gethsemane', 'Golgotha (Calvary)', 'Bethany', 'Capernaum'], answer: 'Golgotha (Calvary)', explanation: 'John 19:17 — "the place of a skull."', tags: ['death-resurrection', 'places'] },
  { id: 'quiz-death-resurrection-2', type: 'tf', prompt: 'Jesus rose from the dead on the third day.', answer: 'True', explanation: '1 Corinthians 15:4 — "he was raised on the third day."', tags: ['death-resurrection'] },
  { id: 'quiz-death-resurrection-3', type: 'fill', prompt: 'In John 19:30, Jesus\' final word from the cross was "It is ___."', answer: 'finished', explanation: 'Tetelestai — "paid in full."', tags: ['death-resurrection'] },
  { id: 'quiz-death-resurrection-4', type: 'mc', prompt: 'Who was the first to see the risen Jesus?', choices: ['Peter', 'Mary Magdalene', 'Thomas', 'John'], answer: 'Mary Magdalene', explanation: 'John 20:16 — "Rabboni!"', tags: ['death-resurrection', 'people-nt'] },
  { id: 'quiz-death-resurrection-5', type: 'matching', prompt: 'Match each event (A–D) to its detail (1–4): A. Last Supper  B. Betrayal  C. Denial  D. Burial — 1. Judas\'s kiss  2. Joseph of Arimathea\'s tomb  3. Bread and cup in the upper room  4. Peter\'s threefold denial', choices: ['A-3, B-1, C-4, D-2', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-2, D-1', 'A-2, B-4, C-1, D-3'], answer: 'A-3, B-1, C-4, D-2', explanation: 'Supper: upper room; betrayal: kiss; denial: threefold; burial: Joseph\'s tomb.', tags: ['death-resurrection'] },
  // ---- OT-OVERVIEW ----
  { id: 'quiz-ot-overview-1', type: 'mc', prompt: 'How many books are in the Old Testament?', choices: ['27', '39', '66', '46'], answer: '39', explanation: 'From Genesis to Malachi.', tags: ['ot-overview'] },
  { id: 'quiz-ot-overview-2', type: 'tf', prompt: 'The Old Testament was written mostly in Hebrew.', answer: 'True', explanation: 'With some Aramaic portions (parts of Daniel and Ezra).', tags: ['ot-overview'] },
  { id: 'quiz-ot-overview-3', type: 'fill', prompt: 'The first five books of the Bible are called the ___.', answer: 'Pentateuch', explanation: 'Genesis through Deuteronomy, the books of Moses.', tags: ['ot-overview'] },
  { id: 'quiz-ot-overview-4', type: 'mc', prompt: 'Which king built the first temple in Jerusalem?', choices: ['David', 'Solomon', 'Hezekiah', 'Josiah'], answer: 'Solomon', explanation: '1 Kings 6 — David planned it; Solomon built it.', tags: ['ot-overview', 'people-ot'] },
  { id: 'quiz-ot-overview-5', type: 'matching', prompt: 'Match each book (A–D) to its subject (1–4): A. Joshua  B. Judges  C. Ruth  D. Esther — 1. A Moabite who joined Israel  2. The conquest of Canaan  3. A Jewish queen in Persia  4. Cycles of sin and deliverance', choices: ['A-2, B-4, C-1, D-3', 'A-4, B-2, C-3, D-1', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], answer: 'A-2, B-4, C-1, D-3', explanation: 'Joshua: conquest; Judges: cycles; Ruth: the Moabite; Esther: queen in Persia.', tags: ['ot-overview'] },
  // ---- NT-OVERVIEW ----
  { id: 'quiz-nt-overview-1', type: 'mc', prompt: 'How many books are in the New Testament?', choices: ['39', '27', '66', '21'], answer: '27', explanation: 'From Matthew to Revelation.', tags: ['nt-overview'] },
  { id: 'quiz-nt-overview-2', type: 'tf', prompt: 'The book of Acts was written by Luke.', answer: 'True', explanation: 'Luke-Acts: two volumes by the physician-historian.', tags: ['nt-overview', 'people-nt'] },
  { id: 'quiz-nt-overview-3', type: 'fill', prompt: 'The last book of the Bible is ___.', answer: 'Revelation', explanation: "John's apocalyptic vision of Christ's victory.", tags: ['nt-overview', 'revelation'] },
  { id: 'quiz-nt-overview-4', type: 'mc', prompt: 'Which is the longest Gospel?', choices: ['Matthew', 'Mark', 'Luke', 'John'], answer: 'Luke', explanation: 'Luke has the most verses and, with Acts, the longest two-volume work.', tags: ['nt-overview'] },
  { id: 'quiz-nt-overview-5', type: 'matching', prompt: 'Match each letter (A–D) to its theme (1–4): A. Romans  B. Hebrews  C. James  D. Jude — 1. "Faith without works is dead"  2. "Contend for the faith"  3. Christ\'s superiority  4. The gospel explained systematically', choices: ['A-4, B-3, C-1, D-2', 'A-1, B-2, C-3, D-4', 'A-3, B-4, C-2, D-1', 'A-2, B-1, C-4, D-3'], answer: 'A-4, B-3, C-1, D-2', explanation: 'Romans: systematic gospel; Hebrews: Christ supreme; James: faith works; Jude: contend.', tags: ['nt-overview'] },

  // ---- PSALMS ----
  { id: 'quiz-psalms-1', type: 'mc', prompt: 'Which is the longest psalm?', choices: ['Psalm 23', 'Psalm 119', 'Psalm 150', 'Psalm 1'], answer: 'Psalm 119', explanation: '176 verses celebrating God\'s word.', tags: ['psalms'] },
  { id: 'quiz-psalms-2', type: 'tf', prompt: 'David wrote all 150 psalms.', answer: 'False', explanation: 'About half are David\'s; others are by Asaph, the sons of Korah, Moses, Solomon, and others.', tags: ['psalms'] },
  { id: 'quiz-psalms-3', type: 'fill', prompt: 'Complete Psalm 23:1: "The LORD is my ___; I shall not want."', answer: 'shepherd', explanation: 'The beloved shepherd psalm of trust and provision.', tags: ['psalms'] },
  { id: 'quiz-psalms-4', type: 'mc', prompt: 'Which is the shortest psalm?', choices: ['Psalm 117', 'Psalm 133', 'Psalm 23', 'Psalm 15'], answer: 'Psalm 117', explanation: 'Just two verses — a call for all nations to praise the LORD.', tags: ['psalms'] },
  { id: 'quiz-psalms-5', type: 'matching', prompt: 'Match each psalm (A–D) to its theme (1–4): A. Psalm 1  B. Psalm 23  C. Psalm 51  D. Psalm 100 — 1. David\'s repentance  2. "Make a joyful noise"  3. The blessed man  4. The shepherd psalm', choices: ['A-3, B-4, C-1, D-2', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-2, D-1', 'A-2, B-1, C-4, D-3'], answer: 'A-3, B-4, C-1, D-2', explanation: 'Psalm 1: the blessed man; 23: the shepherd; 51: repentance; 100: joyful thanksgiving.', tags: ['psalms'] },
  // ---- PROVERBS ----
  { id: 'quiz-proverbs-1', type: 'mc', prompt: 'Proverbs 9:10: "The fear of the LORD is the ___ of wisdom."', choices: ['End', 'Beginning', 'Enemy', 'Replacement'], answer: 'Beginning', explanation: 'Reverent awe of God is where wisdom starts.', tags: ['proverbs'] },
  { id: 'quiz-proverbs-2', type: 'tf', prompt: 'The book of Proverbs was written mainly by Solomon.', answer: 'True', explanation: 'Solomon authored most, with contributions from Agur, Lemuel, and others.', tags: ['proverbs', 'people-ot'] },
  { id: 'quiz-proverbs-3', type: 'fill', prompt: 'Complete Proverbs 3:5: "Trust in the LORD with all your ___."', answer: 'heart', explanation: '"And do not lean on your own understanding."', tags: ['proverbs'] },
  { id: 'quiz-proverbs-4', type: 'mc', prompt: 'Proverbs 6:6 tells the sluggard to learn from the...', choices: ['Lion', 'Ant', 'Eagle', 'Ox'], answer: 'Ant', explanation: '"Go to the ant, you sluggard. Consider her ways, and be wise."', tags: ['proverbs'] },
  { id: 'quiz-proverbs-5', type: 'matching', prompt: 'Match each proverb (A–D) to its saying (1–4): A. 10:4  B. 15:1  C. 16:18  D. 27:17 — 1. Pride goes before destruction  2. The diligent hand makes rich  3. Iron sharpens iron  4. A gentle answer turns away wrath', choices: ['A-2, B-4, C-1, D-3', 'A-4, B-2, C-3, D-1', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], answer: 'A-2, B-4, C-1, D-3', explanation: '10:4 diligence; 15:1 gentleness; 16:18 pride\'s fall; 27:17 sharpening friendship.', tags: ['proverbs'] },
  // ---- THEOLOGY ----
  { id: 'quiz-theology-1', type: 'mc', prompt: '"Theology proper" is the study of...', choices: ['The church', 'God himself', 'The end times', 'Angels'], answer: 'God himself', explanation: 'The foundation of all other theology.', tags: ['theology'] },
  { id: 'quiz-theology-2', type: 'tf', prompt: 'The doctrine of the Trinity teaches that there are three gods.', answer: 'False', explanation: 'One God in three persons — not three gods.', tags: ['theology'] },
  { id: 'quiz-theology-3', type: 'fill', prompt: 'The Trinity is one God existing eternally in three ___.', answer: 'persons', explanation: 'Father, Son, and Holy Spirit — one being, three persons.', tags: ['theology'] },
  { id: 'quiz-theology-4', type: 'mc', prompt: 'Which council (AD 451) defined Christ as two natures in one person?', choices: ['Nicaea', 'Chalcedon', 'Ephesus', 'Constantinople'], answer: 'Chalcedon', explanation: 'Truly God and truly man, "without confusion, without division."', tags: ['theology', 'timeline'] },
  { id: 'quiz-theology-5', type: 'matching', prompt: 'Match each branch (A–D) to its subject (1–4): A. Soteriology  B. Ecclesiology  C. Eschatology  D. Christology — 1. The church  2. Christ  3. Last things  4. Salvation', choices: ['A-4, B-1, C-3, D-2', 'A-1, B-4, C-2, D-3', 'A-2, B-3, C-4, D-1', 'A-3, B-2, C-1, D-4'], answer: 'A-4, B-1, C-3, D-2', explanation: 'Soteriology: salvation; ecclesiology: church; eschatology: last things; Christology: Christ.', tags: ['theology'] },
  // ---- PRAYER ----
  { id: 'quiz-prayer-1', type: 'mc', prompt: 'In the ACTS prayer model, "A" stands for...', choices: ['Asking', 'Adoration', 'Anxiety', 'Agreement'], answer: 'Adoration', explanation: 'Begin prayer with praise for who God is.', tags: ['prayer'] },
  { id: 'quiz-prayer-2', type: 'tf', prompt: 'Jesus taught the Lord\'s Prayer in the Sermon on the Mount (Matthew 6).', answer: 'True', explanation: 'Matthew 6:9-13 — a pattern for praying, not just words to repeat.', tags: ['prayer', 'teachings'] },
  { id: 'quiz-prayer-3', type: 'fill', prompt: 'Complete 1 Thessalonians 5:17: "Pray without ___."', answer: 'ceasing', explanation: 'Ongoing communion with God throughout the day.', tags: ['prayer'] },
  { id: 'quiz-prayer-4', type: 'mc', prompt: 'How many times a day did Daniel pray?', choices: ['Once', 'Three times', 'Seven times', 'Twelve times'], answer: 'Three times', explanation: 'Daniel 6:10 — morning, noon, and evening, windows open toward Jerusalem.', tags: ['prayer', 'people-ot'] },
  { id: 'quiz-prayer-5', type: 'matching', prompt: 'Match each ACTS element (A–D) to its meaning (1–4): A. Adoration  B. Confession  C. Thanksgiving  D. Supplication — 1. Agreeing with God about sin  2. Praise for who God is  3. Asking for needs  4. Gratitude for blessings', choices: ['A-2, B-1, C-4, D-3', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-2, D-1', 'A-3, B-4, C-1, D-2'], answer: 'A-2, B-1, C-4, D-3', explanation: 'Adoration: praise; confession: sin; thanksgiving: gratitude; supplication: requests.', tags: ['prayer'] },
  // ---- FAITH ----
  { id: 'quiz-faith-1', type: 'mc', prompt: 'Hebrews 11:1 defines faith as...', choices: ['Blind optimism', 'Assurance of things hoped for, proof of things not seen', 'Religious emotion', 'Wishful thinking'], answer: 'Assurance of things hoped for, proof of things not seen', explanation: 'Confident trust grounded in evidence, not fantasy.', tags: ['faith'] },
  { id: 'quiz-faith-2', type: 'tf', prompt: 'According to Romans 10:17, faith comes by hearing the word of God.', answer: 'True', explanation: 'Scripture intake is faith\'s food.', tags: ['faith'] },
  { id: 'quiz-faith-3', type: 'fill', prompt: 'Complete Hebrews 11:6: "Without faith it is ___ to please God."', answer: 'impossible', explanation: '"For he who comes to God must believe that he exists."', tags: ['faith'] },
  { id: 'quiz-faith-4', type: 'mc', prompt: 'Jesus\' teaching on mustard-seed faith (Matthew 17:20) shows...', choices: ['Faith must be huge', 'The object of faith matters more than its size', 'Faith is magic', 'Doubt is unforgivable'], answer: 'The object of faith matters more than its size', explanation: 'Small faith in a great God moves mountains.', tags: ['faith', 'teachings'] },
  { id: 'quiz-faith-5', type: 'matching', prompt: 'Match each hero (A–D) to their act of faith (1–4): A. Abraham  B. Rahab  C. Noah  D. Moses — 1. Built the ark  2. Offered Isaac  3. Hid the spies  4. Chose suffering with God\'s people', choices: ['A-2, B-3, C-1, D-4', 'A-1, B-2, C-4, D-3', 'A-4, B-1, C-3, D-2', 'A-3, B-4, C-2, D-1'], answer: 'A-2, B-3, C-1, D-4', explanation: 'Hebrews 11: Abraham offered Isaac; Rahab hid spies; Noah built the ark; Moses chose affliction with Israel.', tags: ['faith', 'people-ot'] },
  // ---- GRACE ----
  { id: 'quiz-grace-1', type: 'mc', prompt: 'Grace is best defined as...', choices: ['God helping those who help themselves', 'God\'s undeserved favor toward sinners', 'A feeling of calm', 'Good manners'], answer: 'God\'s undeserved favor toward sinners', explanation: 'Blessing instead of deserved judgment — always unearned.', tags: ['grace'] },
  { id: 'quiz-grace-2', type: 'tf', prompt: 'Ephesians 2:8-9 teaches we are saved by grace through faith, not by works.', answer: 'True', explanation: '"Not of works, that no one would boast."', tags: ['grace', 'salvation'] },
  { id: 'quiz-grace-3', type: 'fill', prompt: 'Complete 2 Corinthians 12:9: "My grace is ___ for you."', answer: 'sufficient', explanation: '"For my power is made perfect in weakness."', tags: ['grace'] },
  { id: 'quiz-grace-4', type: 'mc', prompt: 'Romans 6:1-2 answers "Shall we continue in sin that grace may abound?" with...', choices: ['"Yes, grace covers it"', '"May it never be!"', '"Only on weekends"', '"Ask your conscience"'], answer: '"May it never be!"', explanation: 'True grace transforms; it never excuses sin.', tags: ['grace', 'paul'] },
  { id: 'quiz-grace-5', type: 'matching', prompt: 'Match each term (A–D) to its meaning (1–4): A. Charis  B. Legalism  C. License  D. Titus 2:12 — 1. Grace misused as an excuse to sin  2. The Greek word for grace  3. Trying to earn God\'s favor by rules  4. Grace teaches us to say "No" to ungodliness', choices: ['A-2, B-3, C-1, D-4', 'A-1, B-2, C-4, D-3', 'A-4, B-1, C-3, D-2', 'A-3, B-4, C-2, D-1'], answer: 'A-2, B-3, C-1, D-4', explanation: 'Charis: grace; legalism: earning; license: abusing; Titus 2:12: grace trains holiness.', tags: ['grace'] },

  // ---- SALVATION ----
  { id: 'quiz-salvation-1', type: 'mc', prompt: 'Ephesians 2:8 says we are saved by...', choices: ['Works', 'Grace through faith', 'Baptism alone', 'Church membership'], answer: 'Grace through faith', explanation: '"And that not of yourselves; it is the gift of God."', tags: ['salvation', 'grace'] },
  { id: 'quiz-salvation-2', type: 'tf', prompt: 'Justification means God declares believing sinners righteous.', answer: 'True', explanation: 'Romans 5:1 — a legal declaration based on Christ\'s work.', tags: ['salvation'] },
  { id: 'quiz-salvation-3', type: 'fill', prompt: 'Complete Acts 16:31: "Believe in the Lord Jesus Christ, and you will be ___."', answer: 'saved', explanation: 'Paul\'s answer to the Philippian jailer.', tags: ['salvation'] },
  { id: 'quiz-salvation-4', type: 'mc', prompt: 'Which best describes the three tenses of salvation?', choices: ['Past only', 'Justified (past), being sanctified (present), to be glorified (future)', 'Future only', 'Earned gradually'], answer: 'Justified (past), being sanctified (present), to be glorified (future)', explanation: 'Saved, being saved, will be saved — all by grace.', tags: ['salvation'] },
  { id: 'quiz-salvation-5', type: 'matching', prompt: 'Match each term (A–D) to its meaning (1–4): A. Justification  B. Sanctification  C. Glorification  D. Adoption — 1. Growing in holiness  2. Made God\'s child  3. Declared righteous  4. Made perfect at Christ\'s return', choices: ['A-3, B-1, C-4, D-2', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-2, D-1', 'A-2, B-4, C-1, D-3'], answer: 'A-3, B-1, C-4, D-2', explanation: 'Justification: declared righteous; sanctification: made holy; glorification: made perfect; adoption: made God\'s child.', tags: ['salvation'] },
  // ---- REVELATION ----
  { id: 'quiz-revelation-1', type: 'mc', prompt: 'The book of Revelation was written by...', choices: ['Paul', 'Peter', 'John the apostle', 'Luke'], answer: 'John the apostle', explanation: 'Revelation 1:1 — John, exiled on Patmos.', tags: ['revelation', 'people-nt'] },
  { id: 'quiz-revelation-2', type: 'tf', prompt: 'Revelation was written to encourage persecuted churches.', answer: 'True', explanation: 'Its message: Christ wins — persevere in hope.', tags: ['revelation'] },
  { id: 'quiz-revelation-3', type: 'fill', prompt: 'Complete Revelation 21:5: "Behold, I am making all things ___."', answer: 'new', explanation: 'God\'s climactic promise of total renewal.', tags: ['revelation'] },
  { id: 'quiz-revelation-4', type: 'mc', prompt: 'How many churches receive letters in Revelation 2–3?', choices: ['Three', 'Seven', 'Twelve', 'Ten'], answer: 'Seven', explanation: 'Ephesus to Laodicea — real churches with timeless messages.', tags: ['revelation'] },
  { id: 'quiz-revelation-5', type: 'matching', prompt: 'Match each church (A–D) to its issue (1–4): A. Ephesus  B. Smyrna  C. Laodicea  D. Philadelphia — 1. Lukewarm self-sufficiency  2. Left its first love  3. An open door; kept Christ\'s word  4. Suffering — "be faithful unto death"', choices: ['A-2, B-4, C-1, D-3', 'A-4, B-2, C-3, D-1', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], answer: 'A-2, B-4, C-1, D-3', explanation: 'Ephesus: lost love; Smyrna: faithful suffering; Laodicea: lukewarm; Philadelphia: open door.', tags: ['revelation'] },
  // ---- PEOPLE-OT ----
  { id: 'quiz-people-ot-1', type: 'mc', prompt: 'Who interpreted Pharaoh\'s dreams in Egypt?', choices: ['Moses', 'Joseph', 'Daniel', 'Aaron'], answer: 'Joseph', explanation: 'Genesis 41 — leading to his rise to power.', tags: ['people-ot', 'genesis'] },
  { id: 'quiz-people-ot-2', type: 'tf', prompt: 'Moses is traditionally considered the author of the first five books of the Bible.', answer: 'True', explanation: 'The Pentateuch is called the "books of Moses" (e.g., John 5:46).', tags: ['people-ot', 'exodus'] },
  { id: 'quiz-people-ot-3', type: 'fill', prompt: 'The prophet ___ was taken up to heaven in a whirlwind.', answer: 'Elijah', explanation: '2 Kings 2:11 — with chariots of fire.', tags: ['people-ot'] },
  { id: 'quiz-people-ot-4', type: 'mc', prompt: 'Who was the first king of Israel?', choices: ['David', 'Saul', 'Solomon', 'Rehoboam'], answer: 'Saul', explanation: '1 Samuel 10 — tall, impressive, but disobedient.', tags: ['people-ot', 'ot-overview'] },
  { id: 'quiz-people-ot-5', type: 'matching', prompt: 'Match each figure (A–D) to the fact (1–4): A. Joshua  B. Gideon  C. Samson  D. Samuel — 1. The fleece and the 300 men  2. A Nazirite of great strength  3. Last judge; anointed Israel\'s kings  4. Led the conquest of Canaan', choices: ['A-4, B-1, C-2, D-3', 'A-1, B-4, C-3, D-2', 'A-2, B-3, C-4, D-1', 'A-3, B-2, C-1, D-4'], answer: 'A-4, B-1, C-2, D-3', explanation: 'Joshua: conquest; Gideon: fleece and 300; Samson: Nazirite strength; Samuel: last judge.', tags: ['people-ot'] },
  // ---- PEOPLE-NT ----
  { id: 'quiz-people-nt-1', type: 'mc', prompt: 'Who was the first Christian martyr?', choices: ['James', 'Stephen', 'Paul', 'Peter'], answer: 'Stephen', explanation: 'Acts 7 — stoned while seeing Christ standing at God\'s right hand.', tags: ['people-nt'] },
  { id: 'quiz-people-nt-2', type: 'tf', prompt: 'The name Barnabas means "son of encouragement."', answer: 'True', explanation: 'Acts 4:36 — he encouraged Paul and the churches.', tags: ['people-nt'] },
  { id: 'quiz-people-nt-3', type: 'fill', prompt: 'The respected Pharisee who advised caution toward the apostles was ___.', answer: 'Gamaliel', explanation: 'Acts 5:34-39 — Paul\'s former teacher.', tags: ['people-nt'] },
  { id: 'quiz-people-nt-4', type: 'mc', prompt: 'Who wrote the most New Testament letters?', choices: ['Peter', 'John', 'Paul', 'James'], answer: 'Paul', explanation: 'Thirteen letters, from Romans to Philemon.', tags: ['people-nt', 'paul'] },
  { id: 'quiz-people-nt-5', type: 'matching', prompt: 'Match each person (A–D) to the fact (1–4): A. Stephen  B. Philip  C. Barnabas  D. Silas — 1. Evangelist to the Ethiopian eunuch  2. Paul\'s missionary companion  3. Sold land; championed Paul  4. First martyr; saw Christ standing', choices: ['A-4, B-1, C-3, D-2', 'A-1, B-4, C-2, D-3', 'A-2, B-3, C-4, D-1', 'A-3, B-2, C-1, D-4'], answer: 'A-4, B-1, C-3, D-2', explanation: 'Stephen: martyr; Philip: Ethiopian; Barnabas: encourager; Silas: companion.', tags: ['people-nt'] },
  // ---- PLACES ----
  { id: 'quiz-places-1', type: 'mc', prompt: 'In which town did Jesus grow up?', choices: ['Bethlehem', 'Nazareth', 'Capernaum', 'Jericho'], answer: 'Nazareth', explanation: 'Matthew 2:23 — "He shall be called a Nazarene."', tags: ['places', 'jesus-ministry'] },
  { id: 'quiz-places-2', type: 'tf', prompt: 'The temple Jesus visited was the original temple built by Solomon.', answer: 'False', explanation: 'Solomon\'s temple was destroyed in 586 BC; Jesus knew Herod\'s rebuilt temple.', tags: ['places', 'timeline'] },
  { id: 'quiz-places-3', type: 'fill', prompt: 'Paul was shipwrecked on the island of ___ on his way to Rome.', answer: 'Malta', explanation: 'Acts 28:1 — "they learned that the island was called Malta."', tags: ['places', 'paul'] },
  { id: 'quiz-places-4', type: 'mc', prompt: 'On which mountain did God give the Ten Commandments?', choices: ['Mount of Olives', 'Mount Sinai', 'Mount Carmel', 'Mount Gerizim'], answer: 'Mount Sinai', explanation: 'Exodus 19-20 — also called Horeb.', tags: ['places', 'exodus'] },
  { id: 'quiz-places-5', type: 'matching', prompt: 'Match each place (A–D) to its significance (1–4): A. Bethlehem  B. Capernaum  C. Gethsemane  D. Patmos — 1. Jesus\' ministry base in Galilee  2. Jesus\' birthplace  3. Where John was exiled  4. Where Jesus prayed before his arrest', choices: ['A-2, B-1, C-4, D-3', 'A-1, B-2, C-3, D-4', 'A-4, B-3, C-2, D-1', 'A-3, B-4, C-1, D-2'], answer: 'A-2, B-1, C-4, D-3', explanation: 'Bethlehem: birth; Capernaum: ministry base; Gethsemane: prayer; Patmos: John\'s exile.', tags: ['places'] },
  // ---- TIMELINE ----
  { id: 'quiz-timeline-1', type: 'mc', prompt: 'Jerusalem fell to Babylon in...', choices: ['722 BC', '586 BC', '538 BC', 'AD 70'], answer: '586 BC', explanation: '2 Kings 25 — temple destroyed, exile began.', tags: ['timeline', 'ot-overview'] },
  { id: 'quiz-timeline-2', type: 'tf', prompt: 'Jesus was born during the reign of Caesar Augustus.', answer: 'True', explanation: 'Luke 2:1 — the census decree brought Joseph and Mary to Bethlehem.', tags: ['timeline', 'jesus-birth'] },
  { id: 'quiz-timeline-3', type: 'fill', prompt: 'Israel wandered in the wilderness for ___ years because of unbelief.', answer: '40', explanation: 'Numbers 14:33-34 — a year for each day of spying.', tags: ['timeline', 'exodus'] },
  { id: 'quiz-timeline-4', type: 'mc', prompt: 'Jerusalem and the second temple were destroyed by Rome in...', choices: ['AD 30', 'AD 64', 'AD 70', 'AD 95'], answer: 'AD 70', explanation: 'As Jesus foretold (Luke 21:6).', tags: ['timeline'] },
  { id: 'quiz-timeline-5', type: 'matching', prompt: 'Match each date (A–D) to its event (1–4): A. 722 BC  B. 586 BC  C. 538 BC  D. 332 BC — 1. Jerusalem falls to Babylon  2. Cyrus\'s decree; the return begins  3. Alexander conquers; Greek culture spreads  4. Israel falls to Assyria', choices: ['A-4, B-1, C-2, D-3', 'A-1, B-4, C-3, D-2', 'A-2, B-3, C-4, D-1', 'A-3, B-2, C-1, D-4'], answer: 'A-4, B-1, C-2, D-3', explanation: '722: Assyria takes Israel; 586: Babylon takes Judah; 538: Cyrus\'s decree; 332: Alexander.', tags: ['timeline'] },
];
